Add initial PI3NN example
ORNL/HydraGNN pull request #100
Opened 2022-02-07 14:59 UTC by streeve

Add general functions for calculating confidence intervals with PI3NN and an example for the existing FePt case.

Things to discuss
- There's some cleanup I need to do where I modified the main examples/training files
- Should any of the UQ functions move to the library? Maybe up/down loaders?
- PI3NN is not currently installed/used in the CI. I'd prefer to wait until tensorflow is optional (not used in the very small part of the library we're calling)
- This only currently works for single task - should not be too difficult to extend

2022-02-08 17:38 UTC, allaffa commented on examples/lsms/lsms.json
> +        "path": {"total": "../../Downloads/FePt"},
Is this intentional?

2022-02-08 17:39 UTC, allaffa commented on examples/lsms/lsms.json
> +            "output_names": ["free_energy_scaled_num_nodes"],
I would not remove the multi-task nature of the run based on `lsms.json`

2022-02-08 17:40 UTC, allaffa commented on examples/lsms_uq.json
> +{
Given indeed that you are creating another .json file specifically for UQ, I do not understand why you changed `lsms.json`

2022-02-08 17:43 UTC, allaffa commented on hydragnn/run_training.py
> +    output_name = model.__str__() + "-mean"
Why did you remove the call to `get_log_name_config`?
Is it needed specifically for UQ or is it a proposed improvement that applies in general to any training?

2022-02-08 17:45 UTC, allaffa commented on examples/lsms/lsms.json
> +        "path": {"total": "../../Downloads/FePt"},
I would not change the original `lsms.json`

2022-02-08 17:53 UTC, streeve commented on examples/lsms/lsms.json
> +        "path": {"total": "../../Downloads/FePt"},
No, like I said in the description, I realized after creating the PR that I need to remove some changes that weren't meant to be included

2022-02-08 17:53 UTC, streeve commented on hydragnn/run_training.py
> +    output_name = model.__str__() + "-mean"
I think adding an option to override the name would be nice, but I will leave the default behavior intact

2022-02-09 04:14 UTC, allaffa commented on examples/uq/uq_pi3nn.py
> +    if dist.is_initialized():
Is the current version tested on MPI ?

2022-02-09 16:27 UTC, streeve commented on examples/uq/uq_pi3nn.py
> +    if dist.is_initialized():
Good point - no it is not

2022-03-09 13:57 UTC, streeve commented
| Do you need additional review for this?

I cleaned up the issues I saw in the diff - another review would be helpful

2022-03-09 16:43 UTC, pzhanggit requested changes
Finish first round review. I will come back later for more reviews

2022-03-09 16:43 UTC, pzhanggit commented on examples/uq/uq_pi3nn.py
> +    ## Question: Should we normalize/denormalize any input/output?
Maybe normalize everything before the three NNs and denormalize them after all of them trained

2022-03-09 16:43 UTC, pzhanggit commented on examples/uq/uq_pi3nn.py
> +def load_model(config, dataset, name):
`dataset` argument is not needed?

2022-03-09 16:43 UTC, pzhanggit commented on examples/uq/uq_pi3nn.py
> +    return up_loaders, down_loaders
`up_sampler` and `down_sampler` need to be returned also since they are needed for shuffling during training in each epoch, see here https://github.com/streeve/HydraGNN/blob/2e93dc50d1744fd5a2e5eaef9f4531ee2ff8093a/hydragnn/train/train_validate_test.py#L94

2022-03-24 14:21 UTC, streeve commented on examples/uq/uq_pi3nn.py
> +    mean_name = out_name + "mean"
mean -> center

2022-03-24 14:21 UTC, streeve commented on examples/uq/uq_pi3nn.py
> +    mean_name = out_name + "mean"
mean -> center

2023-10-31 20:23 UTC, closed without merging