rotational invariance added
ORNL/HydraGNN pull request #102
Opened 2022-02-15 15:03 UTC by allaffa

I am using the PyTorch Geometric transformation called `NormalizeRotation` 
https://pytorch-geometric.readthedocs.io/en/latest/_modules/torch_geometric/transforms/normalize_rotation.html#NormalizeRotation

This transformation computes the eigenvectors if the point could, and transforms data.pos by applying a rotation with respect to the eigenvectors. 

This transformation ensures that data.pos is rotational invariant. Any rotation applied to the graph affects the eigenvectors of the point cloud, but **the relative coordinates of data.pos with respect to the eigenvectors DO NOT CHANGE**

2022-02-15 16:13 UTC, streeve reviewed
This absolutely makes sense - have you seen  accuracy changes on any dataset?

2022-02-15 16:13 UTC, streeve commented on hydragnn/preprocess/serialized_dataset_loader.py
> +        rotational_invariance = NormalizeRotation(max_points=-1, sort=False)
Should this be optional?

2022-02-15 16:15 UTC, allaffa commented on hydragnn/preprocess/serialized_dataset_loader.py
> +        rotational_invariance = NormalizeRotation(max_points=-1, sort=False)
Good question. For now, I think all we do I is predicting properties that are rotational invariant. 
But you never know what happens in the future. In situations where we may need to use it for surface interaction, maybe rotational invariance is not good? I don't know...

2022-02-15 16:18 UTC, allaffa commented
> This absolutely makes sense - have you seen accuracy changes on any dataset?

@streeve 
The unit tests on graphs defined nodal and global properties that are strongly dependent on x-y-z coordinates. Rotating the graph impacts x-y-z coordinates, which in turn impacts the value of global and nodal properties. 

Should I change the existing unit tests or should I create new ones?
Maybe if we make rotation-invariance optional is better to make a new set of unit tests.

2022-02-15 16:57 UTC, pzhanggit commented
> > This absolutely makes sense - have you seen accuracy changes on any dataset?
> 
> @streeve The unit tests on graphs defined nodal and global properties that are strongly dependent on x-y-z coordinates. Rotating the graph impacts x-y-z coordinates, which in turn impacts the value of global and nodal properties.
> 
> Should I change the existing unit tests or should I create new ones? Maybe if we make rotation-invariance optional is better to make a new set of unit tests.

That's interesting. Did you see any change in accuracy? My expectation (correct me if I am wrong) is that the changes made in this PR will not change the unit test.  The nodal and global properties are generated before this function and hence would not be affected. In addition, the rotation preserves the relative position between nodes and hence would not affect the edge construction either.

2022-02-15 17:00 UTC, allaffa commented
> > > This absolutely makes sense - have you seen accuracy changes on any dataset?
> > 
> > 
> > @streeve The unit tests on graphs defined nodal and global properties that are strongly dependent on x-y-z coordinates. Rotating the graph impacts x-y-z coordinates, which in turn impacts the value of global and nodal properties.
> > Should I change the existing unit tests or should I create new ones? Maybe if we make rotation-invariance optional is better to make a new set of unit tests.
> 
> That's interesting. Did you see any change in accuracy? My expectation (correct me if I am wrong) is that the changes made in this PR will not change the unit test. The nodal and global properties are generated before this function and hence would not be affected. In addition, the rotation preserves the relative position between nodes and hence would not affect the edge construction either.

@pzhanggit we explicitly use the absolute values of x-y-z coordinates to compute global properties and nodal properties of the graph. Therefore, the definition of the properties depends on the coordinate system used to define the x-y-z coordinates. Right?

2022-02-15 17:57 UTC, allaffa commented
> > > > > This absolutely makes sense - have you seen accuracy changes on any dataset?
> > > > 
> > > > 
> > > > @streeve The unit tests on graphs defined nodal and global properties that are strongly dependent on x-y-z coordinates. Rotating the graph impacts x-y-z coordinates, which in turn impacts the value of global and nodal properties.
> > > > Should I change the existing unit tests or should I create new ones? Maybe if we make rotation-invariance optional is better to make a new set of unit tests.
> > > 
> > > 
> > > That's interesting. Did you see any change in accuracy? My expectation (correct me if I am wrong) is that the changes made in this PR will not change the unit test. The nodal and global properties are generated before this function and hence would not be affected. In addition, the rotation preserves the relative position between nodes and hence would not affect the edge construction either.
> > 
> > 
> > @pzhanggit we explicitly use the absolute values of x-y-z coordinates to compute global properties and nodal properties of the graph. Therefore, the definition of the properties depends on the coordinate system used to define the x-y-z coordinates. Right?
> 
> Yes, but the properties are defined in `deterministic_graph_data` before "NormalizeRotation" is called to change x-y-z.

Niiiiiiiiiiice :D

2022-02-16 15:45 UTC, allaffa commented
@pzhanggit @streeve 

Can you explain why you would expect improvement in accuracy?

2022-02-16 16:03 UTC, pzhanggit commented
> @pzhanggit @streeve
> 
> Can you explain why you would expect improvement in accuracy?

I am not expecting improvement in accuracy. More specific, I am actually expecting this PR would change nothing in the unit tests or the other cases we have.

2022-02-16 20:58 UTC, streeve commented
> Can you explain why you would expect improvement in accuracy?

For the unit tests, I agree: we don't rotate anything. For QM9 I _would_ expect improvement if it helps the network understand that orientation of any given molecule doesn't matter

2022-02-17 19:32 UTC, allaffa commented
> > Can you explain why you would expect improvement in accuracy?
> 
> For the unit tests, I agree: we don't rotate anything. For QM9 I _would_ expect improvement if it helps the network understand that orientation of any given molecule doesn't matter

**The rotational invariance improves prediction on QM9 (or any other dataset) ONLY IF angle features are used as input features. In the current version of the code, angle features are not used**. 
Therefore, I do not see why the rotational invariance alone should improve the predictions on QM9.
If you still think results should improve, please explain.

2022-02-17 20:21 UTC, streeve commented
Our discussion in person yesterday resolves this discussion - I agree with you. I think that making it optional is important based on the fact that it is not generally useful

2022-02-20 00:02 UTC, allaffa commented
> Our discussion in person yesterday resolves this discussion - I agree with you. I think that making it optional is important based on the fact that it is not generally useful

Thank you! I had committed the changes where I make it optional, but I had forgotten to push. 
Optional flag currently used ;)

2022-02-23 23:44 UTC, allaffa commented on tests/test_graphs.py
> +def pytest_train_model_rotational_invariance(
We don't expect changes, but we also don't expect the code to behave worse. I thought this would be a sanity check that make sure that capabilities built on top of each other are still compatible.

2022-02-24 00:53 UTC, streeve commented on tests/test_graphs.py
> +def pytest_train_model_rotational_invariance(
That's a good point - maybe we only run one model instead of all 5 for now then?

2022-02-24 03:17 UTC, allaffa commented on tests/test_graphs.py
> +def pytest_train_model_rotational_invariance(
Are bargaining? Let's make 2. PNA and GCNN, which are the two we mostly care of so far. :-)

2022-02-24 04:13 UTC, allaffa commented
@streeve 

I reduced the number of models checked with rotation of the data in test_graph.py
Moreover, I created a new test which does the following:

- check consistency before and after rotation of the graph generated from BCT structure associated with FePt
- checks consistency before and after rotation of 10 random graphs

2022-02-24 04:40 UTC, allaffa commented
@streeve @pzhanggit 
I need you guys to check the implementation of this unit test
The assert on the edge length seems to fail whenever I set a tolerance below 1e-5. 
It seems that `torch.geometric.transformations.Distance` does quite a poor job in computing the edge length from the x-y-z coordinates. 
I need you to confirm that I did not create bugs in the code. 

If my code is bug-free, and `torch.geometric.transformations.Distance` really does quite a poor job , we need to be careful. 
Forces are the derivative of the energy with respect to the atom's positions and their neighbors. 
This could affect the use of HydraGNN for prediction on forces from energy.

2022-02-24 14:37 UTC, streeve requested changes
I think the accuracy makes sense for single precision

2022-02-24 14:37 UTC, streeve commented on examples/lsms/lsms.json
> +        "rotational_invariance": true,
Should we switch back to false?

2022-02-24 14:37 UTC, streeve commented on tests/test_rotational_invariance.py
> +def unittest_rotational_invariance():
This looks right to me - I would split everything after creating the structure (random or crystal) into a helper function for the rotation/asserts

2022-02-24 14:37 UTC, streeve commented on tests/test_rotational_invariance.py
> +    compute_edges = RadiusGraph(r=7.0, loop=False)
We could use our function wrappers here

2022-02-24 15:39 UTC, pzhanggit commented
> I think the accuracy makes sense for single precision

Agreed. Default torch type is torch.float32

2022-02-24 16:25 UTC, allaffa commented on examples/lsms/lsms.json
> +        "rotational_invariance": true,
I removed it.

2022-02-24 16:47 UTC, allaffa commented on tests/test_rotational_invariance.py
> +def unittest_rotational_invariance():
The helper function has been created and added to 
`hydrogen.preprocess.util.py`

2022-02-24 17:18 UTC, allaffa commented on tests/test_rotational_invariance.py
> +    compute_edges = RadiusGraph(r=7.0, loop=False)
Done.

2022-02-24 17:38 UTC, pzhanggit reviewed
Looks good to me. One thing is that maybe we do not need full unit tests (PNA and CGCNN) with accuracy checking for rotation, given that data object invariance is checked already in`unittest_rotational_invariance()`. One or two epochs like in qm9/md17 for functionality checking would work IMO.

2022-02-25 04:18 UTC, allaffa commented on tests/test_rotational_invariance.py
> +    compute_edges = RadiusGraph(r=7.0, loop=False)
Done.

2022-02-25 04:34 UTC, allaffa commented
@streeve @pzhanggit 
I am using double precision in the rotational invariance unit test. With double precision, I can lower the tolerance down to 1e-14 and the test still passes. 
With this (more solid and confident( check in place, I removed the additional training of PNA and CGCNN that I was using before. This way, the CI takes approximately the same time as before to run.

2022-02-28 23:17 UTC, streeve commented
@allaffa fixed this up - I think it's ready. @pzhanggit can you take a quick look as well?

2022-02-28 23:18 UTC, streeve approved these changes

2022-03-01 04:14 UTC, pzhanggit approved these changes
Looks good to me.

2022-03-01 04:34 UTC, merged