Add edge lengths
ORNL/HydraGNN pull request #11
Opened 2021-10-20 19:17 UTC by streeve

(From GCNN:)
With @pzhanggit 's help I have found:
- Only PNA and CGConv support
- GIN has an additional version GINE for edges
~~PNA currently breaks because we don't define the `edge_encoder`~~
~~GINE currently breaks because dimensions that don't agree (but I think actually do based on what I've checked)~~

Only implemented for PNA and CG (GINE does not have robust enough support to add). New test matrix only calls for these two models with edge lengths (passes automatically for all others)

2021-11-01 15:20 UTC, streeve commented
Waiting for review on this one

2021-11-01 15:21 UTC, allaffa commented
@streeve 
Reviewing this will be my task on Jira this week :)

2021-11-01 18:27 UTC, streeve commented on hydragnn/unit_tests/test_graphs.py
> +        config["NeuralNetwork"]["Architecture"]["edge_features"] = ["lengths"]
@allaffa I add the edge feature on the fly here

2021-11-02 14:30 UTC, pzhanggit commented on hydragnn/unit_tests/test_graphs.py
> +    if model_type == "PNA" and not use_lengths:
The `if ` condition here is not needed.

2021-11-02 14:43 UTC, streeve commented on hydragnn/unit_tests/test_graphs.py
> +    if model_type == "PNA" and not use_lengths:
But if we modify the config we can't use the original file

2021-11-02 14:45 UTC, pzhanggit commented on hydragnn/unit_tests/test_graphs.py
> +    if model_type == "PNA" and not use_lengths:
We can use the config dictionary, right?

2021-11-02 14:59 UTC, pzhanggit commented on hydragnn/preprocess/serialized_dataset_loader.py
> +        edge_index, edge_length = self.__compute_edges(
@allaffa  I think you are right about something wrong with the normalization. 
@streeve  Could you check line 196 inside self.__compute_edges(...)
`   # Normalize the lengths using min-max normalization
        edge_lengths = (edge_lengths - min(edge_lengths)) / (
            max(edge_lengths) - min(edge_lengths)
        )`. Currently, it uses min/max edge_length in each graph/data sample for normalization, which varies in dataset.

2021-11-02 16:12 UTC, streeve commented on hydragnn/unit_tests/test_graphs.py
> +    if model_type == "PNA" and not use_lengths:
Then we won't test the file interface and miss some bug

2021-11-02 16:38 UTC, pzhanggit commented on hydragnn/unit_tests/test_graphs.py
> +    if model_type == "PNA" and not use_lengths:
Aha, I see what you mean. It is for testing the file overload. Thanks

2021-11-02 19:15 UTC, allaffa commented on hydragnn/preprocess/serialized_dataset_loader.py
> +        edge_index, edge_length = self.__compute_edges(
Yep. the normalization should use `min` and `max` that span the entire dataset.

2021-11-02 19:42 UTC, pzhanggit commented on hydragnn/preprocess/serialized_dataset_loader.py
> +        edge_index, edge_length = self.__compute_edges(
Yeah, it is probably okay for now, given all the samples in the dataset have the same node position, but need to be improved.

2021-11-05 03:18 UTC, allaffa commented
@streeve 
The configuration file `examples/configuraton.json` still causes an error when PNA is used. 
PNA currently breaks because we don't define the edge_encoder. 
I saw that this error was crossed out, so I assumed the issue was solved. But I still get this error when I run the version of the code on this branch.

2021-11-08 19:43 UTC, allaffa commented
@streeve 

The constructor of the `PNA` model that overwrites the constructor of the `Base` model in `PNAStack.py` does not have edge attributes as input parameters. I suspect that the edge length is never used. Am I wrong?

2021-11-16 03:56 UTC, allaffa commented on hydragnn/preprocess/serialized_dataset_loader.py
>          if "subsample_percentage" in config["Variables_of_interest"].keys():
@streeve 
After PR#30 has been merged, I will rebase this one and use `torch_geometric.tramsforms.distance` to compute the edge length. This transformation also provide a Boolean variable to automatically normalize all the edge lengths ion the range (0,1) if it is set to True. 
https://pytorch-geometric.readthedocs.io/en/latest/_modules/torch_geometric/transforms/distance.html#Distance

2021-11-29 18:12 UTC, pzhanggit commented on hydragnn/models/Base.py
> +            if (data.edge_attr is not None) and (
Maybe move this outside of the for loop? We only need to assess data.edge_attr once.

2021-11-29 19:55 UTC, streeve commented on hydragnn/models/Base.py
> +                hasattr(self, "edge_dim")
@allaffa is this for the edge case where the data has `edge_attr`, but the model doesn't support it?

2021-11-29 20:46 UTC, streeve commented on hydragnn/models/Base.py
> +            if (data.edge_attr is not None) and (
Done in the last commit

2021-11-29 20:59 UTC, streeve commented
Cleaned up and rebased on main - thanks for the help @allaffa. This is ready for another review

2021-11-30 03:29 UTC, allaffa commented
> Cleaned up and rebased on main - thanks for the help @allaffa. This is ready for another review @pzhanggit

Your commit history is so clean and every commit is so clearly mapped into changes made to the code...

2021-11-30 13:54 UTC, allaffa commented on hydragnn/models/Base.py
> +                hasattr(self, "edge_dim")
Correct.

2021-11-30 14:40 UTC, pzhanggit commented on hydragnn/preprocess/serialized_dataset_loader.py
> +        compute_edge_lengths = Distance(norm=True, cat=True)
Setting `norm=True` would normalize the distance with the maximum distance in each data sample. Is this by design?

2021-11-30 14:41 UTC, allaffa commented on hydragnn/preprocess/serialized_dataset_loader.py
> +        compute_edge_lengths = Distance(norm=True, cat=True)
I was thinking Both this right now. I want to set it to `False`

2021-11-30 14:47 UTC, pzhanggit commented on hydragnn/models/Base.py
> +            if use_edge_attr:
I was thinking a structure like,
```
if use_edge_attr:
       for conv, batch_norm in zip(self.convs, self.batch_norms):
             c = conv(x=x, edge_index=edge_index, edge_attr=data.edge_attr)
             x = F.relu(batch_norm(c))
else:
       for conv, batch_norm in zip(self.convs, self.batch_norms):
             c = conv(x=x, edge_index=edge_index)
             x = F.relu(batch_norm(c))
```
Not sure how much difference it could make though.

2021-11-30 14:49 UTC, allaffa commented on hydragnn/models/Base.py
> +            if use_edge_attr:
The last commit from Sam does that. The relu call is out of the if-else condition though. 

if use_edge_attr:
       for conv, batch_norm in zip(self.convs, self.batch_norms):
             c = conv(x=x, edge_index=edge_index, edge_attr=data.edge_attr)
else:
       for conv, batch_norm in zip(self.convs, self.batch_norms):
             c = conv(x=x, edge_index=edge_index)

 x = F.relu(batch_norm(c))

2021-11-30 14:56 UTC, pzhanggit commented on hydragnn/models/Base.py
> +            if use_edge_attr:
> 

Not really. For the current code, it still needs to run if-else for every `conv` inside for loop. [Btw, `relu` should be inside for loop in your comment. ]

2021-11-30 15:16 UTC, allaffa commented on hydragnn/models/Base.py
> +            if use_edge_attr:
@pzhanggit 
committed new changes to follow your suggestions. Take a look and let me know. I am debating now whether to NOT perform the normalization on edge_length at all or if we should perform it over the entire dataset

2021-11-30 15:19 UTC, pzhanggit requested changes
It looks good to me. Could you run one case with edge feature on DFT dataset? Wondering how much accuracy improvement it can get.

2021-11-30 15:22 UTC, pzhanggit commented on hydragnn/preprocess/serialized_dataset_loader.py
> +        compute_edge_lengths = Distance(norm=True, cat=True)
We probably still need normalization (otherwise edge feature likely will dominate everything,  given that all other features are normalized). Need to figure out a proper way to do the normalization.

2021-11-30 15:24 UTC, pzhanggit commented on hydragnn/models/Base.py
> +            if use_edge_attr:
Lol, see my comment on normalization above. In short, I think we should have normalization but need do it properly.

2021-11-30 16:42 UTC, streeve commented on hydragnn/models/Base.py
> +import inspect
Remove?

2021-12-01 04:23 UTC, allaffa commented on hydragnn/preprocess/serialized_dataset_loader.py
> +        compute_edge_lengths = Distance(norm=True, cat=True)
Done.

2021-12-02 21:54 UTC, streeve commented on hydragnn/preprocess/serialized_dataset_loader.py
> +            min_edge_length = torch.min(min_edge_length, torch.min(data.edge_attr))
Comment out since we're not using?

2021-12-02 21:54 UTC, streeve commented on hydragnn/preprocess/serialized_dataset_loader.py
> +        dataset[:]=[compute_edges(data) for data in dataset]
This is nice

2021-12-02 21:57 UTC, allaffa commented on hydragnn/preprocess/serialized_dataset_loader.py
> +        dataset[:]=[compute_edges(data) for data in dataset]
@streeve Done.

2021-12-02 22:02 UTC, allaffa commented on hydragnn/preprocess/serialized_dataset_loader.py
> +            min_edge_length = torch.min(min_edge_length, torch.min(data.edge_attr))
@streeve Done.

2021-12-02 22:03 UTC, allaffa commented
> It looks good to me. Could you run one case with edge feature on DFT dataset? Wondering how much accuracy improvement it can get.

@pzhanggit no improvement seen. I will open a separate PR to inver the edge length as edge attributes. Will keep you posted.

2021-12-02 22:19 UTC, pzhanggit commented on hydragnn/preprocess/serialized_dataset_loader.py
> +        min_edge_length = torch.Tensor([float("inf")])
Is it used anywhere?

2021-12-02 22:22 UTC, streeve commented on hydragnn/preprocess/serialized_dataset_loader.py
> +        min_edge_length = torch.Tensor([float("inf")])
Thanks, fixed

2021-12-02 22:23 UTC, pzhanggit approved these changes

2021-12-02 22:54 UTC, merged