delayed transfer of data from host to device
ORNL/HydraGNN pull request #115
Opened 2022-03-08 17:26 UTC by allaffa

Delaying transfer of data from host to device is needed when the dataset is too large to fit entirely onto a single GPU.

2022-03-09 14:58 UTC, jychoi-hpc commented
I will check:
* different places of moving data from CPU to GPU.
* Mak a (config) option for users to specify explicitly (for performance reason)

2022-03-16 04:46 UTC, jychoi-hpc commented
I tested with `examples/lsms` case and found this PR reduces the loading time from 45 sec to 30 sec on Summit. Per-batch data moving from CPU to GPU (line 204 in `Base.py`) was not a big deal.

My observation is the function `update_predicted_values`, which is called after serial data loading, works better on CPU than GPU and thus It is better not call `data.to(device)` as in this PR.

I think this PR can help the GPU out-of-memory error in some degree. Ideally, if we can avoid any this type of post processing calculations after data loading from disk would be the best scenario. We can discuss further after this merge.

2022-03-16 04:47 UTC, jychoi-hpc approved these changes

2022-03-18 17:39 UTC, streeve requested changes
Review didn't show up for some reason

2022-05-07 14:48 UTC, jychoi-hpc commented
I found this PR is necessary for the distributed processing with Ising and OGB. So, I put the most of changes in this PR to #135  and tested working there.  Can we drop this PR and, instead, work on #135?

2022-05-07 14:52 UTC, allaffa commented
> I found this PR is necessary for the distributed processing with Ising and OGB. So, I put the most of changes in this PR to #135 and tested working there. Can we drop this PR and, instead, work on #135?

@jychoi-hpc 
Yes. I am going to close it.

2022-05-07 14:53 UTC, closed without merging