Multi graph size
ORNL/HydraGNN pull request #12
Opened 2021-10-20 19:51 UTC by pzhanggit

2021-11-02 14:41 UTC, streeve approved these changes
Looks good to me - should get Max's approval as well though

2021-11-02 14:41 UTC, streeve commented on hydragnn/models/Base.py
> +        # 2. one graph for one node features (currently implemented)
Aren't both implemented?

2021-11-02 14:44 UTC, pzhanggit commented on hydragnn/models/Base.py
> +        # 2. one graph for one node features (currently implemented)
No, only the second one.

2021-11-21 21:13 UTC, allaffa requested changes
@pzhanggit 
The `configuration.json` file still has the number of nodes as input. If the PR is able to handle graphs of multiple size, this input should be removed and not used anymore.

2021-11-21 21:20 UTC, pzhanggit commented
> @pzhanggit The `configuration.json` file still has the number of nodes as input. If the PR is able to handle graphs of multiple size, this input should be removed and not used anymore.



Good point. Will remove it

2021-11-23 06:06 UTC, pzhanggit commented
> > @pzhanggit The `configuration.json` file still has the number of nodes as input. If the PR is able to handle graphs of multiple size, this input should be removed and not used anymore.
> 
> Good point. Will remove it

See b7b4644ab18a071e6951886fa717911b5d329ba0.

2021-11-23 14:08 UTC, allaffa approved these changes

2021-11-23 14:09 UTC, merged