bug on calculation of the training loss function fixed
ORNL/HydraGNN pull request #127
Opened 2022-03-30 16:52 UTC by allaffa

2022-03-30 18:10 UTC, pzhanggit requested changes
Some general comments:
Not sure if it is a bug, since as the name `loss_rmse` suggests, it was rmse loss. Maybe instead of removing it completely, we keep it as an option, in addition to the MSE. This can also help us reproduce the old results in existing applications.

2022-03-30 18:57 UTC, pzhanggit commented
> I would call it a bug because the RMSE was calculated wrong. We can keep a function to calculate final RMSE, but this should not match previous results

Two things here: RMSE loss based on mini-batch VS. RMSE of entire dataset. It will only give you the former. So if you use it for the later then sure it is a bug.

2022-03-30 20:43 UTC, allaffa commented
@pzhanggit @streeve 
It's ready for review

2022-04-01 13:34 UTC, pzhanggit requested changes
Looks alright to me. A few general comments:
1. Could you make `loss_function_type` optional to users and set default to be 'mse'? Maybe add a few lines in update config function. In this way, our old cases will not break.
2. Add "rmse" as one of the `loss_function_selection`, for two reasons. We can reproduce our old results. And also after our discussion, I think we agree it is a practically legitimate loss function (?).
3. Change variable names like `val_mse` in train_validate_test.py to be someting general, since it is not necessarily mse now.

2022-04-01 18:24 UTC, streeve reviewed
I would approve with Pei's suggested changes. She makes very good points

2022-04-01 18:24 UTC, streeve commented on hydragnn/models/Base.py
> +        self.loss_function = loss_function_selection(loss_function_type)
Very nice

2022-04-11 18:05 UTC, pzhanggit reviewed
Thanks. It looks good to me. One comment is about the unit test of loss function. It is better to put it in a separate test IMO.

2022-04-11 18:05 UTC, pzhanggit commented on tests/test_model_loadpred.py
> +@pytest.mark.parametrize("loss_function_type", ["mae", "mse", "rmse"])
Separate the loss function test in a different test? This test is intended for loading and prediction of a pretrained model.

2022-04-11 18:09 UTC, allaffa commented on tests/test_model_loadpred.py
> +@pytest.mark.parametrize("loss_function_type", ["mae", "mse", "rmse"])
I do not want to make the test heavy weight. You are calling the loss function in this test. I would like just to test if the loss function crashes or not. I thought this would be a good place. But I can change it anyway

2022-04-11 18:21 UTC, pzhanggit commented on tests/test_model_loadpred.py
> +@pytest.mark.parametrize("loss_function_type", ["mae", "mse", "rmse"])
Thanks. The other reason to separate them is that the loss function` ["mae", "mse", "rmse"]` is not going to be checked as desired. The code will check first if a pre-trained model and dataset exist in `log_name`, and if they do, it will load the the old case with whatever loss function used there. If really want to check the loss function here, we probably can add `loss_function_type` as part of `log_name`.

2022-04-12 02:20 UTC, allaffa commented on tests/test_model_loadpred.py
> +@pytest.mark.parametrize("loss_function_type", ["mae", "mse", "rmse"])
@pzhanggit I created a separate `test_loss_function.py`
I only run 2 epochs, definitely not sufficient to check the accuracy, but enough to see if the loss function crashes or not.

2022-04-12 02:21 UTC, allaffa commented on tests/test_model_loadpred.py
> +@pytest.mark.parametrize("loss_function_type", ["mae", "mse", "rmse"])
@streeve 
If I want to check only if a capability crashes or not, without necessarily bothering about the accuracy, is it ok to create a python test without any specific assert?

2022-04-12 16:23 UTC, streeve commented on tests/test_model_loadpred.py
> +@pytest.mark.parametrize("loss_function_type", ["mae", "mse", "rmse"])
Yes, that can be reasonable. That's all the example "tests" do right now

2022-04-12 16:47 UTC, allaffa commented on tests/test_model_loadpred.py
> +@pytest.mark.parametrize("loss_function_type", ["mae", "mse", "rmse"])
Good. So the the new test should be setup correctly.

2022-04-12 20:10 UTC, streeve commented
@allaffa I pushed my suggested changes here. I will approve if it passes

2022-04-13 13:01 UTC, allaffa commented
> @allaffa I pushed my suggested changes here. I will approve if it passes

@streeve Thanks. It passed. Go ahead and approve.

2022-04-13 13:03 UTC, streeve approved these changes

2022-04-13 13:05 UTC, pzhanggit approved these changes

2022-04-14 02:25 UTC, merged