Add a test to load trained model and run prediction for a single sample
ORNL/HydraGNN pull request #129
Opened 2022-03-31 22:35 UTC by pzhanggit

2022-04-01 00:50 UTC, allaffa commented on hydragnn/models/Base.py
> +        if batch is None:
Nice! I remember having similar issues for other codes every time I called **global_mean_pool** on a single data sample.

2022-04-01 00:53 UTC, allaffa commented on tests/test_graph_pred.py
> +    thresholds = 0.75
This threshold every high because the goal of this test is NOT to test the accuracy, but just to make sure that a model is correctly loaded and deployed for predictions. Correct?

2022-04-01 00:55 UTC, allaffa reviewed
Just questions to clarify the set up of the unit test.

2022-04-01 13:14 UTC, pzhanggit commented on tests/test_graph_pred.py
> +    thresholds = 0.75
We want to check model loading and deployment as well as accuracy. The threshold is set to be equal to the maximum sample error we had in https://github.com/ORNL/HydraGNN/blob/215b5e8c93ff945e7da8951adc7fe9f5e3676c9c/tests/test_graphs.py#L126, since we are checking a single randomly selected sample. We could add one more to check the entire test set.

2022-04-01 18:40 UTC, streeve requested changes

2022-04-01 18:40 UTC, streeve commented on tests/test_graph_pred.py
> +    # Read in config settings and override model type.
Not overriding?

2022-04-01 18:40 UTC, streeve commented on tests/test_graph_pred.py
> +def unittest_model_pred(model_dir):
`unittest_model_prediction` + comment? This is just for testing prediction without training?

2022-04-01 18:40 UTC, streeve commented on tests/test_graph_pred.py
> +        config=config["NeuralNetwork"]["Architecture"],
This will have to change based on #127

2022-04-01 18:40 UTC, streeve commented on tests/test_graphs.py
> +from .test_graph_pred import unittest_model_pred
Let's just do all of this in your new file

2022-04-01 18:40 UTC, streeve commented on tests/test_graph_pred.py
> +    ) = hydragnn.preprocess.load_data.dataset_loading_and_splitting(config=config)
Does this rely on another test having created the data? Or am I missing something

2022-04-04 12:38 UTC, pzhanggit commented on tests/test_graph_pred.py
> +def unittest_model_pred(model_dir):
Right.

2022-04-04 12:39 UTC, pzhanggit commented on tests/test_graph_pred.py
> +        config=config["NeuralNetwork"]["Architecture"],
Why? I do not see any changes needed after merging https://github.com/ORNL/HydraGNN/pull/127.

2022-04-04 12:41 UTC, pzhanggit commented on tests/test_graph_pred.py
> +    ) = hydragnn.preprocess.load_data.dataset_loading_and_splitting(config=config)
Yes, this test is for model loading and prediction check only.

2022-04-04 12:48 UTC, pzhanggit commented on tests/test_graphs.py
> +from .test_graph_pred import unittest_model_pred
Sure. One thing is that we want this test to run after the model training done in https://github.com/ORNL/HydraGNN/blob/bf1915c9ac3db508067f365289b674cf201bb7f5/tests/test_graphs.py#L183. Is a place where I can specify the order of unit tests?

2022-04-04 12:49 UTC, pzhanggit commented on tests/test_graph_pred.py
> +    # Read in config settings and override model type.
Could you explain more?

2022-04-04 15:38 UTC, streeve commented on tests/test_graphs.py
> +from .test_graph_pred import unittest_model_pred
Let's use https://pytest-dependency.readthedocs.io/en/latest/usage.html#basic-usage :)

2022-04-04 20:44 UTC, pzhanggit commented on tests/test_graph_pred.py
> +    # Read in config settings and override model type.
Removed.

2022-04-04 20:45 UTC, pzhanggit commented on tests/test_graphs.py
> +from .test_graph_pred import unittest_model_pred
It did not work as we expected, added a manual checking.

2022-04-04 22:08 UTC, streeve approved these changes
Looks good. Maybe we can revisit the pytest-dependency later on

2022-04-04 22:08 UTC, merged