DDP bug fix
ORNL/HydraGNN pull request #136
Opened 2022-05-02 14:29 UTC by pzhanggit

Major features/changes:
1. Fixed a bug in DDP model. The DDP wrapped model was unwrapped (which is not supposed to be) before training. As a result, every process trains its own model with a subset of dataset and there is no synchronization between them. 
2. Fixed a bug about map_location in model loading
3. Added reduce/gather feature for loss log and results collection
4. Added SyncBatchNorm

2022-05-03 02:44 UTC, allaffa commented
@pzhanggit 
I am running the code on FePt. 
I will let you know what I obtain as a result. 
While I am at it, do you want me to run the PR on other datasets that you did not run yourself?

2022-05-03 12:53 UTC, pzhanggit commented
> @pzhanggit I am running the code on FePt. I will let you know what I obtain as a result. While I am at it, do you want me to run the PR on other datasets that you did not run yourself?

Thanks, @allaffa. What datasets you have in mind? So far all I ran is the dftb version of qm9 and in the single head mode. Could you run one case with multihead?

2022-05-03 12:54 UTC, jychoi-hpc commented
This is good. I will run a test on Summit. Which is the part doing "unwrapping" ddp model which is not supposed to happen?

2022-05-03 12:56 UTC, pzhanggit commented on hydragnn/train/train_validate_test.py
> -    model = get_model_or_module(model)
@jychoi-hpc  the unwrapping here

2022-05-03 14:56 UTC, allaffa commented
@pzhanggit 
Now we print the full pytorch tensor on the screen, which causes less digits to be printed out for the individual loss functions on each task. 
We should roll back to there same print formatting as before, maybe calling `torch.item()` instead of printing the entire tensor

2022-05-03 16:40 UTC, streeve reviewed
This looks like a lot of work and I'm very glad the results make more sense once we're actually using DDP :)

2022-05-03 16:40 UTC, streeve commented on hydragnn/utils/model.py
> +    map_location = {"cuda:%d" % 0: get_device_name()}
Maybe we rename these `get_local_device_name` and `get_global_size_and_rank`?

2022-05-03 16:40 UTC, streeve commented on hydragnn/postprocess/visualizer.py
> +        true_values = true_values.cpu().detach().numpy()
Good idea

2022-05-03 16:40 UTC, streeve commented on hydragnn/train/train_validate_test.py
> +            reduce_gpus=True,
reduce_ddp? or reduce_ranks?

2022-05-03 16:40 UTC, streeve commented on hydragnn/train/train_validate_test.py
> +def gather_head_values(head_values):
gather_array_ddp?

2022-05-03 16:40 UTC, streeve commented on hydragnn/train/train_validate_test.py
> +def reduce_loss_stat(total_loss_list, task_loss_list):
Can we reuse one `reduce_values_ddp` function that takes a single list and returns the reduction or updates in place? Unless we really need both options

2022-05-03 16:40 UTC, streeve commented on hydragnn/train/train_validate_test.py
> +            dist.all_reduce(total_error, op=dist.ReduceOp.SUM)
We discussed this a bit already, but I don't see a reason to all_gather instead of gather to rank zero (here and below)

2022-05-03 16:40 UTC, streeve commented on hydragnn/utils/distributed.py
> +def get_distributed_model(model, verbosity=0, SyncBatchNorm=False):
sync_batch_norm

2022-05-03 16:40 UTC, streeve commented on hydragnn/models/Base.py
> -        self._init_node_conv()
This seems unrelated

2022-05-03 16:40 UTC, streeve commented on hydragnn/train/train_validate_test.py
> -    model = get_model_or_module(model)
We should remove that function entirely, right?

2022-05-04 03:15 UTC, allaffa approved these changes

2022-05-04 21:34 UTC, allaffa requested changes

2022-05-04 21:34 UTC, allaffa commented on hydragnn/postprocess/visualizer.py
> +        ax.set_title(title + ", len=" + str(len(x)))
```suggestion
        ax.set_title(title + ", number data samples = " + str(len(x)))
```

2022-05-04 21:34 UTC, allaffa commented on hydragnn/utils/distributed.py
> +    print(
I would use print verbosity here. What do you think?

2022-05-04 21:34 UTC, allaffa commented on hydragnn/train/train_validate_test.py
> +            total_error += loss * data.num_graphs
any reason why you do not access the .item() anymore? 
The older printout to the screen looks better. More digits are printed on the screen with the old way

2022-05-04 21:49 UTC, pzhanggit commented on hydragnn/train/train_validate_test.py
> +            dist.all_reduce(total_error, op=dist.ReduceOp.SUM)
Agreed. We will open an issue and make another PR as we discussed

2022-05-04 21:54 UTC, pzhanggit commented on hydragnn/models/Base.py
> -        self._init_node_conv()
It is relevant. Previously, conv for node is defined even it is not used in the model. However, DDP does not support unused parameters. So we change it to only define it when used.

2022-05-04 22:51 UTC, pzhanggit commented on hydragnn/utils/distributed.py
> +    print(
Probably no difference here since we want to print on every rank

2022-05-04 22:52 UTC, pzhanggit commented on hydragnn/train/train_validate_test.py
> +            total_error += loss * data.num_graphs
Changed

2022-05-04 22:53 UTC, pzhanggit commented on hydragnn/train/train_validate_test.py
> -    model = get_model_or_module(model)
Not sure. It is used also in the model saving. Probably related to the non-DDP mode we were discussing earlier. Let's keep it for now.

2022-05-04 22:53 UTC, pzhanggit commented on hydragnn/utils/model.py
> +    map_location = {"cuda:%d" % 0: get_device_name()}
Not relevant to this PR?

2022-05-04 22:54 UTC, pzhanggit commented on hydragnn/train/train_validate_test.py
> +            reduce_gpus=True,
Done

2022-05-04 22:54 UTC, pzhanggit commented on hydragnn/train/train_validate_test.py
> +def gather_head_values(head_values):
Done

2022-05-04 22:54 UTC, pzhanggit commented on hydragnn/train/train_validate_test.py
> +def reduce_loss_stat(total_loss_list, task_loss_list):
Done

2022-05-04 22:54 UTC, pzhanggit commented on hydragnn/utils/distributed.py
> +def get_distributed_model(model, verbosity=0, SyncBatchNorm=False):
Done

2022-05-04 22:55 UTC, allaffa approved these changes

2022-05-05 03:31 UTC, jychoi-hpc approved these changes

2022-05-06 14:52 UTC, streeve commented on hydragnn/models/Base.py
> +            if self.node_type == "mlp":
Let's switch to a variable loop bound instead

2022-05-06 15:01 UTC, streeve commented on hydragnn/utils/distributed.py
> +    print(
`print_distributed` or remove

2022-05-06 15:40 UTC, pzhanggit commented
> Should we remove `get_model_or_module`? It seems like a good way to make a mistake again

Not sure. It is used also in the model saving. Probably related to the non-DDP mode we were discussing earlier. Let's keep it for now.

2022-05-06 15:53 UTC, pzhanggit commented on hydragnn/utils/distributed.py
> +    print(
Done in 882bac3e57f5cafc07c3f6a69cc7efab35ee9cc7

2022-05-06 15:53 UTC, pzhanggit commented on hydragnn/models/Base.py
> +            if self.node_type == "mlp":
Done in 882bac3e57f5cafc07c3f6a69cc7efab35ee9cc7

2022-05-06 17:11 UTC, streeve commented on hydragnn/train/train_validate_test.py
> +            loss, tasks_loss = model.module.loss(pred, data.y, head_index)
I think this means we always require DDP from now on - the non-DDP doesn't have `module` defined, right?

2022-05-06 17:13 UTC, streeve approved these changes
Not sure if we want to default to True for the reductions, but we can always change it later if it's an issue

2022-05-06 17:14 UTC, pzhanggit commented on hydragnn/train/train_validate_test.py
> +            loss, tasks_loss = model.module.loss(pred, data.y, head_index)
Yes.

2022-05-06 17:17 UTC, merged