Dev ogb design
ORNL/HydraGNN pull request #145
Opened 2022-07-25 17:20 UTC by jychoi-hpc

Sorry for a large PR. This is the update we made for the distributed training of OGB PCQM4Mv2 and AISD HOMO-LUMO dataset. Please feel free leave any questions and comments. 

The main update contains:
* ADIOS file genration
* data loading with ADIOS and DDP 
* Dataset class for OGB and CSCE.

Please merge with the "squash and merge" option when merging to clean up long commit history.

2022-07-25 18:00 UTC, pzhanggit commented
@jychoi-hpc  Thanks for the PR. It is quite complicated. A few general comments:
1. Could we keep only the critical files to demonstrate the examples and remove the others?
2. Could we also reduce the data files to keep some demonstration samples only? It is probably not a good idea to carry the large files around.

2022-07-26 16:59 UTC, jychoi-hpc commented
@pzhanggit  and @allaffa  CI test got an error since GCNN error is slightly larger than the threshold limit set here: https://github.com/jychoi-hpc/HydraGNN/blob/7ed9a9e5619c9eb3179dd2dc5da8eb8dfa9a593b/tests/test_graphs.py#L133

In my local machine GCNN got '0.157268' but the limit is '0.15'. Can we increase the threshold? I am also wondering if this error is deterministic or can be changing depending on randomness (e.g., depending on random sampling).

2022-07-26 19:59 UTC, jychoi-hpc commented
I have removed unnecessary files. I cannot figure out how to set seed perfectly. Just increased threshold for now.

2022-07-27 19:00 UTC, pzhanggit requested changes
Thanks for the changes. I made a few more general comments, mostly about reorganizing/moving functions around and renaming.

2022-07-28 18:16 UTC, jychoi-hpc commented on examples/csce/ogb_utils.py
> +import sys
Make sense. I will move "orb_utils.py" in "utils" folder.

2022-07-28 18:16 UTC, jychoi-hpc commented on examples/ogb/ogb_utils.py
> +import sys
Will do the same thing.

2022-07-28 18:20 UTC, jychoi-hpc commented on hydragnn/train/train_validate_test.py
> +        ## (2022/05) jyc: Temporary fix - stop iteration after profile is done
It's set to stop after profiling is done. I updated the comment.

2022-07-28 18:33 UTC, jychoi-hpc commented on hydragnn/models/Base.py
> +        data = data.to(self.device)
Got it. Will put in `train_validate_test.py`

2022-08-01 17:57 UTC, jychoi-hpc commented on hydragnn/utils/ogbdataset.py
> +from mpi4py import MPI
Make sense. I am renaming it.

2022-08-01 17:58 UTC, jychoi-hpc commented on hydragnn/utils/ogbdataset.py
> +class OGBDataset(torch.utils.data.Dataset):
Make sense. I am renaming it as "AdiosDataset"

2022-08-04 17:45 UTC, pzhanggit reviewed
More comments @jychoi-hpc  Some of the comments are applicable to multiple examples. Could you check them when modifying? Thanks. Also, let me know if any comments unclear.

2022-08-04 17:45 UTC, pzhanggit commented on hydragnn/preprocess/load_data.py
> +        elif isdist:
If ... else ... switch?  We only need one to dump data.

2022-08-04 17:45 UTC, pzhanggit commented on hydragnn/preprocess/load_data.py
> +        elif isdist:
Or, we do not need the new changes?

2022-08-04 17:45 UTC, pzhanggit commented on hydragnn/preprocess/raw_dataset_loader.py
> +                y = x.clone().detach().requires_grad_(False)
Is `y` used to check that the same list is used on all ranks?

2022-08-04 17:45 UTC, pzhanggit commented on hydragnn/preprocess/raw_dataset_loader.py
> +        if self.dist:
Thank you!

2022-08-04 17:45 UTC, pzhanggit commented on hydragnn/preprocess/raw_dataset_loader.py
> +            for name in filelist:
If every rank now reads part of the data files, should we gather them before dumping? Or dump the data into multiple pickle files?

2022-08-04 17:45 UTC, pzhanggit commented on hydragnn/utils/ogb_utils.py
> +def get_node_attribute_name(types):
Change it to return dimension also

2022-08-04 17:45 UTC, pzhanggit commented on hydragnn/utils/ogb_utils.py
> +    # x = torch.tensor([atomic_number], dtype=torch.float).view(-1,1)
Comment line 162, 163, 167, 180, and 182 are not needed any more. Let's remove them

2022-08-04 18:04 UTC, jychoi-hpc commented on hydragnn/utils/ogb_utils.py
> +        node_feature_dim = [1]
Good idea. Then, we add "graph_feature_dims" and "intput_node_feature_dims" in json file, right?

2022-08-04 18:15 UTC, allaffa commented on examples/ising_model/ising_model.json
> +        "compositional_stratified_splitting": 0,
I know that 0 and 1 are treated as `False` and `True`. But maybe it is better to actually use the boolean values?

2022-08-04 18:15 UTC, allaffa commented on examples/ising_model/ising_model.json
> +        "rotational_invariance": 0
I know that 0 and 1 are treated as False and True. But maybe it is better to actually use the boolean values?

2022-08-04 18:16 UTC, allaffa commented on examples/ising_model/ising_model.json
> +            "periodic_boundary_conditions": 0
I know that 0 and 1 are treated as False and True. But maybe it is better to actually use the boolean values?

2022-08-04 18:19 UTC, allaffa commented on examples/ising_model/train_ising.py
> +class AdioGGO:
I think this is a typo. Shouldn't it be `AdiosGGO`?

2022-08-04 18:20 UTC, allaffa commented on examples/ising_model/train_ising.py
> +torch.multiprocessing.set_start_method("fork", force=True)
Why do we need this?

2022-08-04 18:24 UTC, allaffa commented on examples/ising_model/train_ising.py
> +import mpi4py
Do we need this?

2022-08-04 18:32 UTC, pzhanggit commented on hydragnn/utils/ogb_utils.py
> +        node_feature_dim = [1]
Yep, we can add them either in the json file or in the script (train_gap.py).

2022-08-04 18:33 UTC, allaffa commented on examples/ising_model/train_ising.py
> +from mpi4py import MPI
We tried as much as possible to avoid explicit use of MPI directives so far. 
Is there no way to replace the explicit call to MPI with equivalent calls that solely rely on `torch.distributed `?

2022-08-04 18:39 UTC, allaffa commented on examples/ising_model/train_ising.py
> +                assert len(wh) < 2
why do you need this ?

2022-08-04 18:43 UTC, allaffa commented on examples/ising_model/train_ising.py
> +        # os.unlink(path)
If never used, maybe we could remove this?

2022-08-04 18:58 UTC, allaffa commented on examples/ising_model/train_ising.py
> +    def add(self, label, data: torch_geometric.data.Data):
I assume that here you use `data: torch_geometric.data.Data` to suggest what should be the type of the object. However, inside the body of this function you also check if `data` is a list. Is ti really useful to set `data: torch_geometric.data.Data`  then ?

2022-08-04 19:20 UTC, allaffa commented on examples/ising_model/train_ising.py
> +                vdim = wh[0] if len(wh) == 1 else len(arr_list[0].shape) - 1
In line 155 you already define `wh` by accessing the first entry of the numpy array defined by `np.where(m0 != m1)`. Moreover, in line 156 you have an assert that makes the code automatically crash if `wh` has more than one entry. 
Shouldn't `wh[0]` be equal to `wh` itself ?

2022-08-04 19:21 UTC, allaffa reviewed
I added comments and questions to see if I understand correctly what's going on in the code.

2022-08-04 19:44 UTC, jychoi-hpc commented on examples/csce/train_gap.py
> +    var_config["output_names"] = [
Now "graph_feature_dims" is added in the json file (csce_gap.json and orb_gap.json)

2022-08-04 19:58 UTC, allaffa commented on hydragnn/preprocess/load_data.py
> +        super(HydraDataLoader, self).__init__(dataset, **kwargs)
Shouldn't this be `HydraSimpleDataLoader` ?

2022-08-04 20:08 UTC, allaffa commented on hydragnn/preprocess/load_data.py
> +        super(HydraDataLoader, self).__init__(dataset, **kwargs)
Do you ever use this simplified data loader? Why do you have two Hydra data loaders?

2022-08-04 20:13 UTC, allaffa commented on hydragnn/preprocess/load_data.py
>                  pickle.dump(minmax_node_feature, f)
if the data is distributed and multiple processes executed this "dumping" (which I think is a writing), is it possible that this line causes a race condition?

2022-08-04 20:28 UTC, jychoi-hpc commented on examples/ising_model/train_ising.py
> +                self.download()
It was experimental. I am removing now.

2022-08-04 21:10 UTC, jychoi-hpc commented on examples/ising_model/train_ising.py
> +        # os.unlink(path)
It was experimental. I will remove

2022-08-12 13:19 UTC, pzhanggit reviewed
More minor comments... The comments are mostly about removing unused lines and functions.

2022-08-12 13:19 UTC, pzhanggit commented on hydragnn/utils/ogb_utils.py
> +
```suggestion
```

2022-08-12 13:19 UTC, pzhanggit commented on hydragnn/utils/ogb_utils.py
> +def datasets_load(datafile, sampling=None, seed=None):
Move this function to ogb/train_gap.py ? to be consistent with csce

2022-08-12 13:19 UTC, pzhanggit commented on hydragnn/utils/ogb_utils.py
> +    return smiles, yvals, strset
```suggestion
```

2022-08-12 13:19 UTC, pzhanggit commented on hydragnn/utils/ogb_utils.py
> +
```suggestion
```

2022-08-12 13:19 UTC, pzhanggit commented on hydragnn/utils/ogb_utils.py
> +import sys
Rename this file to be something like smiles_utils.py?

2022-08-12 15:05 UTC, jychoi-hpc commented on examples/csce/train_gap.py
> +    atomtypes_dict = {}
Great. I will remove.

2022-08-12 15:12 UTC, jychoi-hpc commented on examples/csce/train_gap.py
> +        isub = -1
Will remove.

2022-08-13 15:28 UTC, allaffa commented on examples/ogb/train_gap.py
> +                print(valueset[:, 2].mean(), valueset[:, 2].std())
@pzhanggit 
The command lines with your suggestions seem to be exactly the same as the ones that are already written in the code. Maybe @jychoi-hpc already made your suggested changes ?

2022-08-13 15:47 UTC, allaffa commented on hydragnn/utils/print_utils.py
> +def iterate_tqdm(iterator, verbosity_level, *args, **kwargs):
what is the advantaged of having *args and **kwargs as additional arguments for `iterate_tqdm` ?

2022-08-13 15:48 UTC, allaffa reviewed
I added a few more questions

2022-08-14 02:42 UTC, jychoi-hpc commented on examples/csce/train_gap.py
> +        _trainset = dataset_lists[0]
Yes, I will add.

2022-08-14 02:47 UTC, jychoi-hpc commented on examples/csce/train_gap.py
> +    else:
Great. Thank you for the check I have added "pickle" read.

2022-08-14 02:53 UTC, jychoi-hpc commented on hydragnn/preprocess/utils.py
> +def check_if_graph_size_variable_mpi(train_loader, val_loader, test_loader):
I will remove `check_if_graph_size_variable_mpi` as well as `calculate_PNA_degree_mpi` as the MPI versions will not be used anymore.

2022-08-14 02:57 UTC, jychoi-hpc commented on hydragnn/train/train_validate_test.py
> +        loader.device = get_device()
I will remove them. It was an experimental feature.

2022-08-14 02:59 UTC, jychoi-hpc commented on examples/csce/train_gap.py
> +    (train_loader, val_loader, test_loader,) = hydragnn.preprocess.create_dataloaders(
It is correct. DistributedSampler will do subset for each process.

2022-08-14 03:00 UTC, jychoi-hpc commented on examples/ogb/train_gap.py
> +                print(valueset[:, 2].mean(), valueset[:, 2].std())
Not sure when I did. Anyway, it is gone now.

2022-08-14 03:01 UTC, jychoi-hpc commented on hydragnn/utils/ogb_utils.py
> +
Great. I will remove.

2022-08-14 03:04 UTC, jychoi-hpc commented on hydragnn/utils/ogb_utils.py
> +    return smiles, yvals, strset
Thanks. I will remove.

2022-08-14 03:04 UTC, jychoi-hpc commented on hydragnn/utils/ogb_utils.py
> +
Great. I will remove.

2022-08-14 03:06 UTC, jychoi-hpc commented on hydragnn/utils/ogb_utils.py
> +import sys
I think this is a good suggestion. I will rename it.

2022-08-14 03:17 UTC, jychoi-hpc commented on hydragnn/utils/print_utils.py
> +def iterate_tqdm(iterator, verbosity_level, *args, **kwargs):
tqdm has many options we can use. We can pass such options with "*args, **kwargs" (This is also optional parameters. It will not break any previous usage).  

For example, I have added "desc" option in `tqdm`s in `train_validate_test.py`:
```
        for data in iterate_tqdm(
            test_loader, verbosity, desc="Collecting node feature"
        ):
```

2022-08-14 03:43 UTC, jychoi-hpc reviewed
Thank you for the detailed check. I think I have addressed all the comments. Feel free to check and leave further comments.

2022-08-14 13:25 UTC, pzhanggit commented on examples/ogb/train_gap.py
> +                print(valueset[:, 2].mean(), valueset[:, 2].std())
> 

Not following exactly what you meant @allaffa . The lines (that were suggested to be removed) were there in this round of review.

2022-08-15 20:11 UTC, pzhanggit commented on examples/csce/train_gap.py
> +    (train_loader, val_loader, test_loader,) = hydragnn.preprocess.create_dataloaders(
Then do we need to gather loaded samples after each process's reading for example in `SimplePickleDataset` so that every process have all the samples?

2022-08-15 20:46 UTC, pzhanggit commented on hydragnn/preprocess/utils.py
> +def check_if_graph_size_variable_mpi(train_loader, val_loader, test_loader):
This one is missing?

2022-08-15 21:04 UTC, jychoi-hpc commented on examples/csce/train_gap.py
> +    (train_loader, val_loader, test_loader,) = hydragnn.preprocess.create_dataloaders(
SimplePickleDataset is created to compare Adios reading vs single pickle file per graph reading in the paper (ie, number of graphs == number of pickle file). So, no need to gather is needed here. If this is confusing, I can remove since this feature is added for the paper writing.

2022-08-15 21:09 UTC, jychoi-hpc commented on hydragnn/preprocess/utils.py
> +def check_if_graph_size_variable_mpi(train_loader, val_loader, test_loader):
Sorry. Not clear to me what you are asking. Do you mean you cannot find "check_if_graph_size_variable_mpi"? I have deleted it in favor of using "check_if_graph_size_variable_dist".

2022-08-15 21:15 UTC, jychoi-hpc commented on hydragnn/utils/ogb_utils.py
> +def datasets_load(datafile, sampling=None, seed=None):
Good point. I agree with you. I will move to `ogb/train_gap.py`

2022-08-15 21:16 UTC, pzhanggit commented on hydragnn/preprocess/utils.py
> +def check_if_graph_size_variable_mpi(train_loader, val_loader, test_loader):
The opposite. I meant, the functions are still there in the script and need to be removed.

2022-08-15 21:16 UTC, pzhanggit commented on hydragnn/preprocess/utils.py
> +def check_if_graph_size_variable_mpi(train_loader, val_loader, test_loader):
Are they not showing up on your side?

2022-08-15 21:21 UTC, pzhanggit commented on examples/csce/train_gap.py
> +    (train_loader, val_loader, test_loader,) = hydragnn.preprocess.create_dataloaders(
I see. Somehow I was confused and thought that the number of pickles files is equal to the number of processes and each process will only read the subset in the corresponding pickle file. Now it is clear. No need to remove. Thanks for the explanation.

2022-08-15 21:23 UTC, jychoi-hpc commented on hydragnn/preprocess/utils.py
> +def check_if_graph_size_variable_mpi(train_loader, val_loader, test_loader):
I see. I have removed and don't see the function "check_if_graph_size_variable_mpi" anymore from my side.

2022-08-15 21:28 UTC, pzhanggit commented on hydragnn/preprocess/utils.py
> +def check_if_graph_size_variable_mpi(train_loader, val_loader, test_loader):
Quite strange, I can still see the function here, https://github.com/jychoi-hpc/HydraGNN/blob/bd80d1027895865dfaa4c9874cfa6fb7a7b6ce85/hydragnn/preprocess/utils.py#L33.

2022-08-15 21:38 UTC, jychoi-hpc commented on hydragnn/preprocess/utils.py
> +def check_if_graph_size_variable_mpi(train_loader, val_loader, test_loader):
I am sorry. My fault. I haven't saved the file. The text tool I am using is quite good at maintaining cache :) I just pushed.

2022-08-16 20:59 UTC, jychoi-hpc commented on hydragnn/preprocess/raw_dataset_loader.py
> +            for name in filelist:
It makes sense more to use the old way. I just revert the change back to the previous one. I.e., setting `config["Dataset"]["name"]` in `train_ising.py`. Thank you for double-checking.

2022-08-19 02:04 UTC, allaffa commented on hydragnn/utils/adiosdataset.py
> +        self.preflight = False
@jychoi-hpc 
What is the utility of preflight? Is it used for pre-fetching future data and store it in cache?

2022-08-19 02:50 UTC, allaffa commented on examples/csce/train_gap.py
> +        help="preprocess only. Adios saving and no train",
@jychoi-hpc 
Actually, if args.preonly == True, you also allow to write the data on .pkl files. 
Am I right? If this is the case, then "Adios saving and no train" is confusing

2022-08-19 02:51 UTC, allaffa reviewed
I added a couple of more comments

2022-08-19 16:53 UTC, jychoi-hpc commented on hydragnn/utils/adiosdataset.py
> +        self.preflight = False
I am sorry for the lack of comment.  Returning empty object is intentional. It is an experimental feature I made for the paper. I named as a 'preflight'. 
It will collect only index of data to load and "populate" call will load all the data data from disk. I was testing this for the paper.

I put more comments for the options available in `AdiosDataset`.

2022-08-19 16:58 UTC, jychoi-hpc commented on examples/csce/train_gap.py
> +        help="preprocess only. Adios saving and no train",
Agree. I will change as follows:
```
    parser.add_argument(
        "--preonly",
        action="store_true",
        help="preprocess only (no training)",
    )
```

2022-08-19 18:04 UTC, allaffa commented on examples/ising_model/train_ising.py
> +                assert len(wh) < 2
In line 155 you are extracting the first element oof the bumpy array. 
If this is the case, should it never be that `len(wh)=1`

2022-08-19 18:19 UTC, allaffa commented on hydragnn/utils/adiosdataset.py
> +            Opption to cache data object which was already read
```suggestion
            Opption to cache data object which was already read
```

2022-08-19 18:19 UTC, allaffa commented on hydragnn/utils/adiosdataset.py
> +            Opption to cache data object which was already read
@jychoi-hpc 

I know I am very picky here, but there is a typo :)

2022-08-19 18:20 UTC, allaffa reviewed
New comments

2022-08-19 18:57 UTC, allaffa commented on hydragnn/utils/adiosdataset.py
> +                assert len(wh) < 2
@jychoi-hpc 
Sorry but I still struggle to understand why this assert is needed. 
In the previous line, you explicitly extract the first entry of the bumpy array. 
Once you do that, shouldn't it be alway true that `len(wh)=1` ?

2022-08-19 18:57 UTC, allaffa reviewed
New comments added.

2022-08-19 20:28 UTC, pzhanggit reviewed
Add two more comments...
It looks fine to me now. I have verified the codes run fine on Summit for examples: csce, ising, ogb, and lsms. As soon as the current comments are resolved, I will approve the PR.

2022-08-20 01:15 UTC, jychoi-hpc commented on hydragnn/utils/adiosdataset.py
> +                assert len(wh) < 2
Not a problem. `np.where` returns a list of arrays:
```
>>> m0 = np.array([6,4])
>>> m1 = np.array([100,4])
>>> np.where(m0 != m1)
(array([0]),)
```
`np.where(m0 != m1)**[0]**` extracts the array of matching indices. 
Then, `len(wh)` can be either 0 (for scalar) or 1 (for 1d shape vector)

2022-08-20 01:22 UTC, jychoi-hpc commented on hydragnn/utils/distributed.py
> +            dist.init_process_group(backend=backend, init_method="env://")
I thought "env://` is the default way in pytorch. It looks like both are same:
https://pytorch.org/docs/stable/distributed.html#torch.distributed.init_process_group

2022-08-20 01:34 UTC, jychoi-hpc commented on examples/csce/train_gap.py
> +    if not args.noadios:
Nice finding. It's the error. I will fix.

2022-08-21 16:38 UTC, pzhanggit approved these changes
Thanks for fixing all my comments. It looks good to me now.

2022-08-24 01:54 UTC, allaffa approved these changes

2022-08-24 13:22 UTC, merged