Lsms example
ORNL/HydraGNN pull request #147
Opened 2022-09-12 11:47 UTC by pzhanggit

Update lsms  following the style in ising example

2022-09-14 12:31 UTC, jychoi-hpc requested changes
I just made a few comments on cleaning up the code and using data loader.

2022-09-14 12:31 UTC, jychoi-hpc commented on examples/lsms/lsms.py
> +        import adios2 as ad2
You can remove this line. `AdiosDataset` will handle it.

2022-09-14 12:31 UTC, jychoi-hpc commented on examples/lsms/lsms.py
> +            import adios2 as ad2
You can remove this line. AdiosDataset will handle it.

2022-09-14 12:31 UTC, jychoi-hpc commented on hydragnn/train/train_validate_test.py
> +            test_loader.dataset, verbosity, desc="Collecting node feature"
You can remove `.dataset` and just use `test_loader`. Using `test_loader.dataset` will slow down for other cases with larger dataset (e.g., OGB, CSCE).

2022-09-14 12:49 UTC, pzhanggit commented on hydragnn/train/train_validate_test.py
> +            test_loader.dataset, verbosity, desc="Collecting node feature"
We aim to collect node information, e.g., number of nodes for each graph, here for visualization. If we remove `.dataset`, the information we get is batch info, e.g., total number of nodes of the entire batch (=num_nodes*batch_size for constant graph size), instead of for each graph. Yeah, it can be slow for larger datasets. Any suggestions to improve it?

2022-09-14 13:36 UTC, jychoi-hpc commented on hydragnn/train/train_validate_test.py
> +            test_loader.dataset, verbosity, desc="Collecting node feature"
After the conversation, you can leave as it is. It makes sense to me.

2022-09-14 14:03 UTC, jychoi-hpc approved these changes

2022-09-18 15:00 UTC, allaffa commented on examples/lsms/lsms.py
> +        "--preonly",
Unless the flag `--preonly` is explicitly called when `lsms.py` is launched, the conversion of raw data into .pkl files is never executed. 
If one starts with just raw data files and launches `lsms.py`, the code crashes because the code skips the creation of the .pkl files, searches for the .pkl files assuming that they already exists, and crashes because it does no find them.

2022-09-18 15:03 UTC, allaffa commented on examples/lsms/lsms.py
> +        "--preonly",
But I like the idea of providing the options of only converting the raw data into either .pkl or adios without necessarily kicking off the training.

2022-09-18 15:09 UTC, allaffa commented on examples/lsms/lsms.py
> +    if args.preonly:
Unless the flag --preonly is explicitly called when lsms.py is launched, the conversion of raw data into .pkl files is never executed.
If one starts with just raw data files and launches lsms.py, the code crashes because the code skips the creation of the .pkl files, searches for the .pkl files assuming that they already exists, and crashes because it does no find them.

2022-09-18 15:10 UTC, allaffa commented on examples/lsms/lsms.py
> +
I think the the if condition at line 69 should me removed. 
Instead, here you should say 

```suggestion
if args.preonly:
    break
```

2022-09-18 15:20 UTC, allaffa commented on hydragnn/utils/config_utils.py
> +        + config["Dataset"]["name"][: config["Dataset"]["name"].rindex("_")]
This assumes that the data name always contain "_" in it. 
Do we really need this?

2022-09-18 15:21 UTC, allaffa requested changes
First round of review done

2022-09-19 12:10 UTC, pzhanggit commented on examples/lsms/lsms.py
> +    if args.preonly:
Good point. I will make update the `--preonly` part. Was following the same style in other examples.

2022-09-19 12:15 UTC, pzhanggit commented on hydragnn/utils/config_utils.py
> +        + config["Dataset"]["name"][: config["Dataset"]["name"].rindex("_")]
> This assumes that the data name always contain "_" in it. 
---Good point, I should have used `rfind`. Will update this part.
Do we really need this?
---Yes, because the `config["Dataset"]["name"] = "%s_%d" % (datasetname, rank)` and we do not want `rank` show up  in output folder name.

2022-09-19 13:41 UTC, pzhanggit commented on examples/lsms/lsms.py
> +
We do not want to remove line 69 because we may want to load existing pickle/adios data with train/test/val splits for reproducibility or continuous training. 
In e6c26ede419d1bad68652df18b7a05793f894c65, I add a new flag `loadexistingsplit` and make it default to do raw data conversion&splitting unless specified. Let me know what you think.

2022-09-19 17:58 UTC, allaffa approved these changes

2022-09-19 17:58 UTC, allaffa commented
@pzhanggit I just re-ran the `lsms.py` Python script on debug mode on my laptop. 
Seems good to me.

2022-09-19 17:59 UTC, allaffa commented on hydragnn/utils/config_utils.py
> +        + config["Dataset"]["name"][: config["Dataset"]["name"].rindex("_")]
@pzhanggit If you run the code in sequential and config["Dataset"]["name"] doe snot contain a "_", the code crashes.

2022-09-19 18:00 UTC, allaffa reviewed
@pzhanggit one more comment on "_"

2022-09-19 18:01 UTC, allaffa requested changes
One more comment on "_"

2022-09-19 18:04 UTC, allaffa approved these changes

2022-09-19 18:05 UTC, allaffa commented
@pzhanggit sorry for the confusion. I saw the last change on the "_". I think this PR is ready to merge

2022-09-19 19:01 UTC, merged