use_zero option added for ZeroRedundancyOptimizer
ORNL/HydraGNN pull request #148
Opened 2022-09-15 20:33 UTC by allaffa

2022-09-16 01:43 UTC, pzhanggit requested changes

2022-09-16 01:43 UTC, pzhanggit commented on hydragnn/utils/optimizer.py
> +        use_zero = config["optimizer"]["use_zero"]
It should be `config['Training']["optimizer"]` here, to be consistent with `ci.json` input and` test_optimizer.py`. Currently `ZeroRedundancyOptimizer` will not be called.

2022-09-16 01:44 UTC, allaffa commented on hydragnn/utils/optimizer.py
> +    if "use_zero" in config["optimizer"]:
```suggestion
    if "use_zero" in config['Training']["optimizer"]:
```

2022-09-16 01:45 UTC, allaffa commented on hydragnn/utils/optimizer.py
> +        use_zero = config["optimizer"]["use_zero"]
```suggestion
        use_zero = config['Training']["optimizer"]["use_zero"]
```

2022-09-16 01:54 UTC, allaffa commented on hydragnn/utils/optimizer.py
> +        use_zero = config["optimizer"]["use_zero"]
@pzhanggit sorry but I do not agree. the `config` passed in input to the routines here is not the entire config. It is just the section associated with the Training.

2022-09-16 02:51 UTC, pzhanggit commented on hydragnn/utils/optimizer.py
> +        use_zero = config["optimizer"]["use_zero"]
I meant config['Training']["use_zero"].

2022-09-16 02:58 UTC, pzhanggit commented on hydragnn/utils/optimizer.py
> +        use_zero = config["optimizer"]["use_zero"]
Okay, after checking line 81 of `/hydragnn/run_training.py`, it should be `config` and `config["use_zero"]`, because `["use_zero"]` is not defined as item in `["optimizer"]`?

2022-09-16 03:51 UTC, allaffa commented on hydragnn/utils/optimizer.py
> +        use_zero = config["optimizer"]["use_zero"]
Yes, that is correct. I was thinking whether I should define `["use_zero"]` as item in `["optimizer"]` or not. 
`ZeroRedundancyOptimizer` is a wrapper that applies to all optimizers. What would you do?

2022-09-16 11:41 UTC, pzhanggit commented on hydragnn/utils/optimizer.py
> +        use_zero = config["optimizer"]["use_zero"]
Either one works for me. Putting ["use_zero"] as item in ["optimizer"] is neater but requires more changes to the code.

2022-09-16 12:56 UTC, allaffa commented on hydragnn/utils/optimizer.py
> +        use_zero = config["optimizer"]["use_zero"]
If I were to create a new subsection in the configure file, both ["use_zero"] and ["learning_rate"] would go under ["optimizer"], whereas everything else would remain where it already is. Correct?

2022-09-16 22:15 UTC, allaffa commented
@pzhanggit @jychoi-hpc  This PR is ready for another round.

2022-09-19 13:56 UTC, pzhanggit commented on hydragnn/utils/optimizer.py
> +    if "use_zero_redundancy" in config["Optimizer"]["type"]:
Typo? 
```suggestion
    if "use_zero_redundancy" in config["Optimizer"]:
```

2022-09-19 13:56 UTC, pzhanggit commented on hydragnn/utils/optimizer.py
> +    if config["Optimizer"]["type"] == "SGD":
Since now all the Optimizer related parameters have been put inside `config["Optimizer"]`, we can pass `config["Optimizer"]` to `select_optimizer` to get rid of all the `["Optimizer"]` in `optimizer.py`.

2022-09-19 21:34 UTC, jychoi-hpc approved these changes
Great. This looks good to me. I tested on Summit with the OGB case and it went ok.

2022-09-23 15:07 UTC, pzhanggit approved these changes

2022-09-26 18:43 UTC, merged