Timers
ORNL/HydraGNN pull request #15
Opened 2021-10-26 16:28 UTC by allaffa

2021-11-01 15:19 UTC, streeve requested changes
There are some unresolved comments plus one more new one

2021-11-01 15:19 UTC, streeve commented on hydragnn/run_training.py
> +    print_timers(verbosity)
We should print in `run_prediction` as well

2021-11-03 16:35 UTC, streeve commented on hydragnn/run_prediction.py
> +    print_timers(verbosity)
Before return :)

2021-11-03 16:36 UTC, streeve commented on hydragnn/utils/time_utils.py
> +                for key, value in Timer.timers_min.items()
Add the same sorting as individual timers

2021-11-03 18:35 UTC, allaffa commented on hydragnn/run_prediction.py
> +    print_timers(verbosity)
LOL. Thanks :)

2021-11-03 19:12 UTC, streeve approved these changes

2021-11-03 19:13 UTC, merged