Add atomic descriptors from Mendeleev
ORNL/HydraGNN pull request #156
Opened 2022-11-16 21:54 UTC by pzhanggit

Add atomic descriptors from Mendeleev (https://mendeleev.readthedocs.io/en/stable/index.html)

2022-11-17 19:18 UTC, allaffa commented on tests/test_atomicdescriptors.py
> +    return_code = subprocess.call(["python", file_path])
Very nice! I did not know about this.

2022-11-17 19:25 UTC, allaffa commented on hydragnn/utils/atomicdescriptors.py
> +                return mendeleev.element(element).atomic_number - 57 + 3
Can you explain why you have to do this?

2022-11-17 19:28 UTC, allaffa commented on hydragnn/utils/atomicdescriptors.py
> +if __name__ == "__main__":
Do we need this call? I think you used this to make sure that the code developed was working fine. But I don't think this main function should stay. Do you agree?

2022-11-17 19:30 UTC, allaffa commented on hydragnn/utils/atomicdescriptors.py
> +if __name__ == "__main__":
I think the code would be better structures if this function were to be moved inside `test_atomicdescriptors.py`
Do you agree?

2022-11-17 19:30 UTC, allaffa reviewed
First round of review

2022-11-18 13:58 UTC, pzhanggit commented on hydragnn/utils/atomicdescriptors.py
> +                return mendeleev.element(element).atomic_number - 57 + 3
`mendeleev` library returns `None` for those elements.

2022-11-18 13:59 UTC, pzhanggit commented on hydragnn/utils/atomicdescriptors.py
> +if __name__ == "__main__":
Both would work. I prefer to have it here for convenient/easy testing/debugging. What do you think?

2022-11-18 20:12 UTC, allaffa requested changes

2022-11-18 20:12 UTC, allaffa commented on hydragnn/utils/atomicdescriptors.py
> +                return mendeleev.element(element).atomic_number - 57 + 3
Just throw an error if Mendeleev does not support information for a specific element, regardless of whether it is natural or synthetic.

2022-11-23 15:07 UTC, allaffa approved these changes

2022-11-23 15:08 UTC, merged