Adding dataset class
ORNL/HydraGNN pull request #163
Opened 2023-02-05 05:17 UTC by jychoi-hpc

This is a PR for dataset restructuring by merging "loading rawdata" and "loading serialized data" to avoid intermediate "pkl" file saving.

Brief description of added/updated dataset related classes is as follows:
* BaseDataset as a base dataset class for HydraGNN (an abstract class). 
* RawDataset is based on previous RawDataLoader plus load_serialized_data
* AdiosDataset, PickleDataset, SerializedDataset are added
* Adios writer, pickle writer, and serialized writer are added to save data in different formats

Examples updated to see usages:
* lsms example: updated to use LSMSDataset(RawDataset) and SerializedDataset
* ising example: updated to use LSMSDataset and DistDataset

2023-02-13 20:52 UTC, pzhanggit reviewed
Thank you @jychoi-hpc  I really like this PR. I have a few comments mostly on cleaning up stuff in this round. I will need another round to test this changes in runs.

2023-02-13 20:52 UTC, pzhanggit commented on examples/ising_model/train_ising.py
> +            SimplePickleWriter(
Do we need to pass `comm=comm` here?

2023-02-13 21:05 UTC, allaffa commented on examples/ising_model/train_ising.py
>          """
The function `nsplit` is used so often in so many examples and utilities...
I would suggest that we create a standalone file in `hydragnn.utils` where we define it once

2023-02-13 21:15 UTC, allaffa commented on hydragnn/utils/rawdataset.py
> +def tensor_divide(x1, x2):
Is `tensor_divide` even used anymore anywhere? 
If it is not used anywhere, we may consider wither deleting it once for all or put it inside `hydragnn.utils` in case it may become useful again one day

2023-02-13 21:16 UTC, allaffa commented on hydragnn/utils/rawdataset.py
> +def comm_reduce(x, op):
Should `comm_reduce` also be moved to a separate file inside `hydrogen.utils`?

2023-02-13 21:22 UTC, allaffa commented on hydragnn/utils/rawdataset.py
> +class RawDataset(BaseDataset, ABC):
In the previous PR#161 I named this class `AbstractRawDataset`. Should we preserve that denomination?

2023-02-13 21:23 UTC, allaffa commented on hydragnn/utils/rawdataset.py
> +            if self.data_format == "LSMS":
In PR#161 I had moved this `if` condition out of the AbstractRawDataset and made it part of the `LSMSDataset` class. Is it possible to do the same here?

2023-02-13 21:25 UTC, allaffa requested changes
First round of reviews.

2023-02-14 03:01 UTC, jychoi-hpc commented on hydragnn/utils/rawdataset.py
> +        self.__load_raw_data(sampling=self.sampling)
Make sense. I will change.

2023-02-14 03:01 UTC, jychoi-hpc commented on hydragnn/utils/rawdataset.py
> +        self.graph_feature_col = config["Dataset"]["graph_features"]["column_index"]
Thank you for checking. I will remove.

2023-02-14 03:02 UTC, jychoi-hpc commented on hydragnn/utils/rawdataset.py
> +        assert len(self.graph_feature_name) == len(self.graph_feature_col)
You are right. It's repeating. I will remove.

2023-02-14 03:08 UTC, jychoi-hpc commented on hydragnn/utils/rawdataset.py
> +    def __load_serialized_data(self):
How about "build_edge"?

2023-02-14 03:10 UTC, jychoi-hpc commented on hydragnn/utils/rawdataset.py
> +class LSMSDataset(RawDataset):
Agree. Will make separate files.

2023-02-14 03:29 UTC, jychoi-hpc commented on examples/ising_model/train_ising.py
> +            SimplePickleWriter(
Yes, we need. Thank you for catching!!

2023-02-14 03:30 UTC, jychoi-hpc commented on examples/lsms/lsms.py
> +        config["NeuralNetwork"]["Variables_of_interest"]
My mistake. Something left over after copy and paste. I will remove.

2023-02-14 03:47 UTC, jychoi-hpc commented on hydragnn/utils/rawdataset.py
> +def nsplit(a, n):
Good suggestion. I agree. Will make it as a common function.

2023-02-14 03:53 UTC, jychoi-hpc commented on hydragnn/utils/rawdataset.py
> +def tensor_divide(x1, x2):
I find It is used in two places. I will make it as a common function to be reusable.

2023-02-14 03:56 UTC, jychoi-hpc commented on hydragnn/utils/rawdataset.py
> +def comm_reduce(x, op):
Great. I find two places used. I will make it as a common function as you suggest.

2023-02-14 04:09 UTC, jychoi-hpc commented on hydragnn/utils/rawdataset.py
> +class RawDataset(BaseDataset, ABC):
Agree. I will rename.

2023-02-14 04:16 UTC, jychoi-hpc commented on hydragnn/utils/rawdataset.py
> +            if self.data_format == "LSMS":
Thank you for catching. I moved "charge_density_update_for_LSMS" to lsmsdataset but didn't delete here. I will clean up.

2023-02-14 04:18 UTC, jychoi-hpc commented on hydragnn/utils/rawdataset.py
> +    def __charge_density_update_for_LSMS(self, data_object: Data):
Same as above. I already put "charge_density_update_for_LSMS" function to lsms class but didn't clean here. I will update.

2023-02-18 18:38 UTC, allaffa approved these changes

2023-02-18 19:15 UTC, jychoi-hpc commented
The CI test error was caused because multiple processes overwrote "config.json" and left it as a corrupted file. I made a common function `save_config` and replaced throughout the codes.

I think I addressed all the previous comments. Please check again and leave further comments.

2023-02-20 17:07 UTC, pzhanggit reviewed
Thanks for fixing the comments. It looks good to me in general. I added a few more comments. Most of them are minor, except for the one in `lsms.py`. I think the current implementation might cause trouble in `pickle` and `mpirun -n 2` mode.

2023-02-20 19:46 UTC, jychoi-hpc commented on hydragnn/utils/model.py
> +def save_config(config, log_name, path="./logs/"):
Totally agree. Will move.

2023-02-20 19:56 UTC, jychoi-hpc commented on examples/ising_model/train_ising.py
> +        testset = AdiosDataset(fname, "testset", comm, **opt)
Adios reads "minmax" automatically. It is same for SimplePickleDataset. I think the following line made a confusion:
```
minmax_node_feature = trainset.minmax_node_feature
```
It is not needed anymore. I will remove

2023-02-20 21:42 UTC, jychoi-hpc commented
@pzhanggit I addressed your second reviews. Please leave further comments.

2023-02-21 02:53 UTC, pzhanggit commented
> @pzhanggit I addressed your second reviews. Please leave further comments.

@jychoi-hpc  have you pushed any new changes? I could not see them from my side.

2023-02-21 05:02 UTC, jychoi-hpc commented
@pzhanggit Sorry. I just updated. Can you check again?

2023-02-22 00:24 UTC, pzhanggit approved these changes
Thanks for fixing my comments! It looks all good to me.

2023-02-22 00:25 UTC, pzhanggit commented on examples/lsms/lsms.py
> +        config["NeuralNetwork"]["Variables_of_interest"]
@jychoi-hpc  Just noticed this line is still there?

2023-02-22 02:44 UTC, merged

2023-02-22 02:44 UTC, allaffa commented
@pzhanggit @jychoi-hpc 
Merged :-)