skip connection option added
ORNL/HydraGNN pull request #165
Opened 2023-02-22 03:07 UTC by allaffa

2023-02-22 04:06 UTC, allaffa commented
@pzhanggit @jychoi-hpc 
I put it as a WIP because the multi-heads of the `GATv2Conv` layer change the dimensional of the variable `x` across multiple message passing layers. If I set `self.heads=1`, everything works well also for this layer However, for any number of `self.heads` larger than 1, the code crashes. 
For now, the skip connection is allowed for all the layers except for `GATv2Conv`. I would like to probe more into the  `GATv2Conv` layers and see if there is a practical way to apply the skip connection also for this layer.

2023-04-14 15:19 UTC, allaffa commented
@pzhanggit @jychoi-hpc 
I activated this PR to kick off the review process :)

2023-04-14 18:38 UTC, jychoi-hpc approved these changes
It looks good to me. As long as we solve the conflict, I think it is ok to merge.

2023-04-14 19:36 UTC, allaffa commented
> It looks good to me. As long as we solve the conflict, I think it is ok to merge.

@jychoi-hpc I manually solved the conflicts and rebase to maintain a linear history on the main branch. Would you mind re-controlling that I di don't remove anything of what you did? Thanks.

2023-04-14 19:46 UTC, pzhanggit reviewed
Look good to me too. I only have a few minor comments. Will approve once they are fixed and the tests pass.

2023-04-14 19:46 UTC, pzhanggit commented on hydragnn/models/Base.py
> +        for i, (conv, batch_norm) in enumerate(zip(self.convs, self.batch_norms)):
Remove `i` and `enumerate` since not used anymore

2023-04-14 19:46 UTC, pzhanggit commented on hydragnn/models/Base.py
> +
Not needed?

2023-04-14 19:46 UTC, pzhanggit commented on hydragnn/models/Base.py
> +class Conv(torch.nn.Module):
Do we want to move the three new classes to the end of the file?

2023-04-14 19:46 UTC, pzhanggit commented on hydragnn/models/create.py
>      elif model_type == "SchNet":
`skip_connection` also for `SchNet`?

2023-04-14 19:50 UTC, allaffa commented on hydragnn/models/Base.py
> +class Conv(torch.nn.Module):
The new classes are important building blocks used in the rest of the script. 
Logically, I like more when the building blocks are defined first, before they are used by any other function or class. 
Does it make sense?

2023-04-14 19:53 UTC, pzhanggit commented on hydragnn/models/Base.py
> +class Conv(torch.nn.Module):
> The new classes are important building blocks used in the rest of the script. Logically, I like more when the building blocks are defined first, before they are used by any other function or class. Does it make sense?

Sounds good to me too.

2023-04-15 01:05 UTC, pzhanggit requested changes
Need to update `forward` function. That skip connection is defined in `self.conv_shared` but not called in `forward` function. It is still calling the old `self.convs`.

2023-04-15 01:05 UTC, pzhanggit commented on hydragnn/models/Base.py
> +        self.conv_shared = ConvSequential(*self.layers)
Hmmmm,  just noticed that `self.conv_shared` is defined but never used in `forward` function? Still the old one `self.convs` is used.

2023-04-15 12:13 UTC, allaffa commented on hydragnn/models/Base.py
> +        self.conv_shared = ConvSequential(*self.layers)
This is a mistake of mine. In merging manually I definitely messed up something. 
@jychoi-hpc would you mind checking ? I had to` force push`. Therefore, locally what you did does not show up anymore.

2023-04-16 13:56 UTC, jychoi-hpc commented on hydragnn/models/Base.py
> +        self.conv_shared = ConvSequential(*self.layers)
I pushed the chagnes for the forward function to your local repo: https://github.com/allaffa/HydraGNN/pull/3 Once you merge, it will show up here.

2023-04-18 14:05 UTC, allaffa commented
@pzhanggit @jychoi-hpc 
Thanks. I turned on again the PR for an additional review :-)

2023-10-31 20:23 UTC, closed without merging