Checkpoint Training Model
ORNL/HydraGNN pull request #187
Opened 2023-06-26 15:40 UTC by JustinBakerMath

Basic checkpointing for training based on the synchronized `validation_loss` performance metric.

Can be turned on by adding
```
"Training" : {
    "Checkpoint" : true,
}
```
with additional `checkpoint_freq` argument for the frequency of checkpointing (`default=10`)
```
"Training" : {
    "Checkpoint" : true,
    "checkpoint_freq" : 10,
}
```

2023-06-26 17:35 UTC, allaffa commented on tests/inputs/ci.json
> +        "Checkpoint": true,
In terms of indentation, it is best that checkpoint be encapsulated within "Training"

2023-06-26 21:57 UTC, allaffa commented on tests/inputs/ci.json
> +            "EarlyStopping": true,
Would you mind adding this section to all the CI.json file where at least 10 epochs are performed?

2023-06-26 21:58 UTC, allaffa requested changes
We should add the additional input to all the JSON file of CI tests that perform at least 10 epochs.

2023-06-27 13:36 UTC, JustinBakerMath commented
After revisiting this: `checkpoint_freq` and `min_perf_metric` aren't ideally compatible.

If the goal is to use `min_perf_metric` to checkpoint, then there should be a *warmup* rather than a frequency.

I've refactored this, replacing `checkpoint_freq` with `checkpoint_warmup` for a *warmup* to checkpointing.

Two print lines are also included
- (every epoch) indicate best performance metric 
- (upon saving) indicate new checkpoint with performance metric.

2023-06-27 20:05 UTC, allaffa commented on hydragnn/utils/model.py
> +        if (perf_metric > self.min_perf_metric + self.min_delta) or (
The call to `save_model` has no input parameter that varies over the iteration count. How do you make sure that different checkpoints are saved in directories with different path names?

2023-07-06 15:30 UTC, allaffa commented
@jychoi-hpc 

Hi Jong. Justin implemented a checkpoint restart which saves a copy of the model when the validation loss function gets reduced at a new iteration. A warm-up waiting is applied at earlier iterations of the training to avoid saving too many models at the beginning. 
I was wondering if the PR may cause too many bottlenecks with significant slow-down for training. 
Any thoughts on this?

2023-07-14 14:30 UTC, jychoi-hpc approved these changes
I checked on Summit. It works for me. Since users can control (delay, etc) through json file, I think it is ok.

2023-07-14 15:34 UTC, merged