setup file added
ORNL/HydraGNN pull request #25
Opened 2021-11-15 19:04 UTC by allaffa

2021-11-15 19:31 UTC, streeve requested changes

2021-11-15 19:31 UTC, streeve commented on setup.py
> +    version="1.0",
I would start with 0.1-dev or 0.1

2021-11-15 19:31 UTC, streeve commented on setup.py
> +    author="Massimiliano Lupo Pasini, Samuel Temple Reeve, Pei Zhang, Jong Youl Choi",
Marko?

2021-11-15 22:13 UTC, streeve commented
What you started with is probably sufficient, but we may as well add other easy categories (e.g. license): https://pythonhosted.org/an_example_pypi_project/setuptools.html 

Do you want to replace `requirements.txt` or keep both?

2021-11-16 01:37 UTC, allaffa commented on setup.py
> +    author="Massimiliano Lupo Pasini, Samuel Temple Reeve, Pei Zhang, Jong Youl Choi",
He is nor an author of the repository

2021-11-16 01:45 UTC, allaffa commented
> What you started with is probably sufficient, but we may as well add other easy categories (e.g. license): https://pythonhosted.org/an_example_pypi_project/setuptools.html
> 
> Do you want to replace `requirements.txt` or keep both?

@streeve I would like to keep both

2021-11-16 13:41 UTC, streeve requested changes

2021-11-16 13:41 UTC, streeve commented on setup.py
> +    version="1.0",
After discussing we can leave as is and plan to release after current PRs are mereged

2021-11-16 13:41 UTC, streeve commented on setup.py
> +    author="Massimiliano Lupo Pasini, Samuel Temple Reeve, Pei Zhang, Jong Youl Choi",
Not actively, but his contributions are still in the repo

2021-11-16 13:41 UTC, streeve commented on setup.py
> +    long_description=read("README"),
Need to add the `read` helper function

2021-11-16 14:02 UTC, allaffa commented on setup.py
> +    author="Massimiliano Lupo Pasini, Samuel Temple Reeve, Pei Zhang, Jong Youl Choi",
The list of people added here is going to reflect the name of people listed as authors in the technical transfer.

2021-11-16 17:12 UTC, pzhanggit approved these changes

2021-11-16 17:14 UTC, streeve approved these changes

2021-11-16 17:15 UTC, merged