Energy linear regression
ORNL/HydraGNN pull request #269
Opened 2024-07-23 21:06 UTC by jychoi-hpc

This is to add a script for energy linear regression.

2024-07-23 21:07 UTC, jychoi-hpc commented
I am checking for all dataset. Please don't merge yet.

2024-07-24 02:07 UTC, allaffa commented on examples/multidataset/energy_linear_regression.py
> +            data.energy = data.energy - np.dot(hist, x)
```suggestion
            data.energy = data.energy - np.dot(hist, x) - _e
```

2024-07-24 02:08 UTC, allaffa commented on examples/multidataset/energy_linear_regression.py
> +            data.energy = data.energy - np.dot(hist, x)
This means that you have to store `_e`, so that you can retrieve its value later on if needed.

2024-07-24 02:16 UTC, allaffa requested changes
Besides removing the linear term from the energy, we also need to remove the mean value. 
Both linear terms and mean value need to be stored somewhere.

2024-07-25 00:52 UTC, allaffa approved these changes

2024-07-25 14:08 UTC, frobnitzem commented
I have an alternative implementation, which should be compared to be sure we are doing the same thing.

2024-07-25 15:20 UTC, allaffa commented
> I have an alternative implementation, which should be compared to be sure we are doing the same thing.

@frobnitzem 
Thanks. Please update this PR, providing your own alternative implementation, an Jong and I will compare the two implementations for consistency checks.

2024-07-25 19:34 UTC, frobnitzem commented
I wouldn't subtract the mean energy - as this makes the energy model unphysical (E = E_0 + \sum_z c_z n_z).  However, the results check out with the mean/covariance based computation:
```
$ python3 regression.py MPTrj.npz  | head -n5
# 1580227 samples, mean_E = -6.193764163751678, sigma_E = 1.847178354885813, sigma_fit = 0.6926824090165239
# Z c_Z m_Z sigma_Z
1 -3.4515251449541444 0.03201297273784663 0.11519684739878065
2 -0.25242553354522296 2.499640874380706e-05 0.00431143556356506
3 -3.131654896166989 0.026181752747806215 0.07941033289624111

$ python3 regression.py MPTrj-v2.npz  | head -n5
# 1580227 samples, mean_E = -5.234825150397457e-10, sigma_E = 0.6926824093226412, sigma_fit = 0.6926824093226411
# Z c_Z m_Z sigma_Z
1 -4.690768751132216e-09 0.0320129727378466 0.11519684739878065
2 -6.457415234849677e-08 2.4996408743807057e-05 0.004311435563565056
3 -3.145968856761228e-08 0.026181752747806188 0.07941033289624111
```

I do wonder why He (Z=2) is present in MPTrj.

2024-07-25 20:39 UTC, allaffa commented on examples/multidataset/energy_linear_regression.py
> +    _e = _e - emean
```suggestion
    #_e = _e - emean
```

2024-07-25 20:40 UTC, allaffa commented on examples/multidataset/energy_linear_regression.py
> +                    -np.dot(hist, x) - emean,
```suggestion
                    -np.dot(hist, x),# - emean,
```

2024-07-25 20:40 UTC, allaffa commented on examples/multidataset/energy_linear_regression.py
> +            data.energy -= np.dot(hist, x) + emean
```suggestion
            data.energy -= np.dot(hist, x) #+ emean
```

2024-07-25 20:41 UTC, allaffa commented on examples/multidataset/energy_linear_regression.py
> +            energy_list.append((data.energy.item(), -np.dot(hist, x) - emean))
```suggestion
            #energy_list.append((data.energy.item(), -np.dot(hist, x) - emean))
            energy_list.append((data.energy.item(), -np.dot(hist, x)))
```

2024-07-25 20:43 UTC, allaffa commented on examples/multidataset/energy_linear_regression.py
> +                    data.energy.item() - np.dot(hist, x) - emean,
```suggestion
                    data.energy.item() - np.dot(hist, x),# - emean,
```

2024-07-25 20:44 UTC, allaffa commented on examples/multidataset/energy_linear_regression.py
> +            np.savez(f"{args.modelname}_energy.npz", energy=energy_arr, emean=emean)
```suggestion
            #np.savez(f"{args.modelname}_energy.npz", energy=energy_arr, emean=emean)
            np.savez(f"{args.modelname}_energy.npz", energy=energy_arr)
```

2024-07-25 20:45 UTC, allaffa commented on examples/multidataset/energy_linear_regression.py
> +    adwriter.add_global("energy_mean", np.array(emean))
```suggestion
    #adwriter.add_global("energy_mean", np.array(emean))
```

2024-07-25 20:49 UTC, allaffa requested changes
@jychoi-hpc 
let's see if with the changes I propose here (in which we do not remove the mean value of the energy) we maintain consistency with the results obtained by @frobnitzem

2024-07-25 20:50 UTC, allaffa commented
> I wouldn't subtract the mean energy - as this makes the energy model unphysical (E = E_0 + \sum_z c_z n_z). However, the results check out with the mean/covariance based computation:
> 
> ```
> $ python3 regression.py MPTrj.npz  | head -n5
> # 1580227 samples, mean_E = -6.193764163751678, sigma_E = 1.847178354885813, sigma_fit = 0.6926824090165239
> # Z c_Z m_Z sigma_Z
> 1 -3.4515251449541444 0.03201297273784663 0.11519684739878065
> 2 -0.25242553354522296 2.499640874380706e-05 0.00431143556356506
> 3 -3.131654896166989 0.026181752747806215 0.07941033289624111
> 
> $ python3 regression.py MPTrj-v2.npz  | head -n5
> # 1580227 samples, mean_E = -5.234825150397457e-10, sigma_E = 0.6926824093226412, sigma_fit = 0.6926824093226411
> # Z c_Z m_Z sigma_Z
> 1 -4.690768751132216e-09 0.0320129727378466 0.11519684739878065
> 2 -6.457415234849677e-08 2.4996408743807057e-05 0.004311435563565056
> 3 -3.145968856761228e-08 0.026181752747806188 0.07941033289624111
> ```
> 
> I do wonder why He (Z=2) is present in MPTrj.

Could you retrieve which atomistic structures contains He ?

2024-07-26 17:21 UTC, jychoi-hpc commented
I removed "mean(e)". If the histogram (shared in the Teams) looks ok, let's this branch is ready to merge.

2024-07-26 18:20 UTC, allaffa approved these changes

2024-07-29 16:14 UTC, merged