Energy forces
ORNL/HydraGNN pull request #278
Opened 2024-09-06 18:04 UTC by RylieWeaver

@allaffa Let me know what you think of this PR for energy and force computation. It should follow exactly what we discussed before. Some notable things:

(1) It requires data.energy and data.forces to exist and be named this way
(2) It balances force and energy prediction weighting implicitly, since we aren't able to pass multiple weights in single-task learning
(3) Compute forces is an argument to be specified in the json within "Training".
      - If specified, it throws errors for anything other than nodal single task learning, as well as any model that doesn't
         use positional information for prediction

2024-09-06 18:24 UTC, allaffa reviewed
@RylieWeaver 
This is exactly what we discussed and looks awesome. 
Have you tried it with Lenndard Jones to make sure that it is compatible?

2024-09-06 18:37 UTC, RylieWeaver commented
@allaffa 

Awesome, thanks.

I was able to get it to work with Lennard Jones after some small changes to LJ's dataset creation and inference. For example, we now have `data.energy` and`'data.forces` instead of `data.y` and `data.forces_pre_scaled`. A next step could be updating the LennardJones example to that.

Do not merge it yet, because I am resolving any issues with the GitHub tests, but will let you know when they are passed.

2024-09-06 20:30 UTC, allaffa commented
> @allaffa 
> 
> 
> 
> Awesome, thanks.
> 
> 
> 
> I was able to get it to work with Lennard Jones after some small changes to LJ's dataset creation and inference. For example, we now have `data.energy` and`'data.forces` instead of `data.y` and `data.forces_pre_scaled`. A next step could be updating the LennardJones example to that.
> 
> 
> 
> Do not merge it yet, because I am resolving any issues with the GitHub tests, but will let you know when they are passed.
> 
> 
> 
> 

@RylieWeaver 
As long as the CI tests do not pass, I would not be allowed to merge this PR anyway. We have explicitly forbidden this option in the settings of the GitHub repository.

2024-09-06 22:23 UTC, allaffa commented
@RylieWeaver 

I think it would be good to also include a mew test that the CI workflow must execute where we check this capability to make sure that future changes in the code do not break it

2024-09-06 22:26 UTC, RylieWeaver commented
> @RylieWeaver As long as the CI tests do not pass, I would not be allowed to merge this PR anyway. We have explicitly forbidden this option in the settings of the GitHub repository.

Ok, that's good.

2024-09-06 22:27 UTC, RylieWeaver commented
> @RylieWeaver
> 
> I think it would be good to also include a mew test that the CI workflow must execute where we check this capability to make sure that future changes in the code do not break it

Ok, I can include this. Any model that includes positional information should be able to predict forces in this method. Should we use that list for the testing?

2024-09-09 14:53 UTC, RylieWeaver commented
@allaffa I believe I'll need to create a new dataset inside `hydragnn/serialized_dataset` for this testing, so that data.forces and data.energy are available. It seems like most of the other data is generated randomly from [0.0, 0.5, 1.0].

Is this correct and is random generation is fine for the forces/energy as well?

2024-09-09 15:44 UTC, allaffa commented
> @allaffa I believe I'll need to create a new dataset inside `hydragnn/serialized_dataset` for this testing, so that data.forces and data.energy are available. It seems like most of the other data is generated randomly from [0.0, 0.5, 1.0].
> 
> 
> 
> Is this correct and is random generation is fine for the forces/energy as well?

@RylieWeaver 
I have an idea that I would like to run by you. 
What about adding a frozen version of the LJ code as an additional example, where the example first generates the data, saves it into files, and then uses it for training? We don't need to generate many data samples and traing it fully. We just need to make sure that the training kicks off correctly without errors.

2024-09-09 17:26 UTC, RylieWeaver commented
> > @allaffa I believe I'll need to create a new dataset inside `hydragnn/serialized_dataset` for this testing, so that data.forces and data.energy are available. It seems like most of the other data is generated randomly from [0.0, 0.5, 1.0].
> > Is this correct and is random generation is fine for the forces/energy as well?
> 
> @RylieWeaver I have an idea that I would like to run by you. What about adding a frozen version of the LJ code as an additional example, where the example first generates the data, saves it into files, and then uses it for training? We don't need to generate many data samples and traing it fully. We just need to make sure that the training kicks off correctly without errors.

@allaffa Yeah, I think this will be good to add LJ to the main branch. Would you be free to hammer out the specifics? Your calendar seems booked. If not, that's fine to hash out here what this will look like:

(1) So, what I think you're saying is to transfer the whole LJ example to the `hydragnn/examples` directory, including dataset creation, train.py, and json files. This will pull from both your fork and `PyTorch_interatomic_potentials`. It should be able to run similar to the qm9 example,  where `____.py` will detect if there is data and generate it if not. 
(2) Then, would the `examples/LJ` dataset be simply copy-pasted over to `hydragnn/serialized_dataset` to use for examples, or is that unrelated? It would be 500 data points in line with the other examples

2024-09-14 01:23 UTC, allaffa commented on hydragnn/models/DIMEStack.py
> +            act=Sigmoid(),  # Sigmoid instead of SiLU here promotes stability when we have a linear decoder at the start of convolution (especially for random data examples in test_graphs.py)
Is this really necessary?

2024-09-16 18:44 UTC, allaffa requested changes

2024-09-16 18:44 UTC, allaffa commented on examples/LennardJones/Forces_Scatterplot.png
@RylieWeaver 
No pictures

2024-09-16 18:44 UTC, allaffa commented on examples/LennardJones/LJ_vlad_atomic_forces.json
@RylieWeaver 
Do you need this file?

2024-09-16 18:44 UTC, allaffa commented on examples/LennardJones/LJ_multitask.json
@RylieWeaver 
Do you need this file?

2024-09-16 18:44 UTC, allaffa commented on examples/LennardJones/LJ_vlad_total_energy.json
@RylieWeaver 
Do you need this file?

2024-09-16 18:44 UTC, allaffa commented on examples/LennardJones/train_vlad_atomic_forces.py
@RylieWeaver 
Do you need this file?

2024-09-16 18:44 UTC, allaffa commented on examples/LennardJones/train_vlad_total_energy.py
@RylieWeaver 
Do you need this file?

2024-09-16 19:00 UTC, RylieWeaver commented on examples/LennardJones/train_vlad_total_energy.py
@allaffa No, there are a lot of things that I don't think are necessary here, but I wanted to ask before taking out. Does it sound good to take out all the `Vlad` files?

2024-09-16 19:00 UTC, RylieWeaver commented on examples/LennardJones/graph_utils.py
@allaffa Thanks, I'll look into that.

2024-09-16 19:00 UTC, RylieWeaver commented on examples/LennardJones/Forces_Scatterplot.png
@allaffa sounds good

2024-09-16 19:06 UTC, RylieWeaver commented on examples/LennardJones/train_vlad_total_energy.py
@allaffa Additionally, I think we could take out `inference.py`, since it would be a rare use case to only want to see predicted energy but not forces.

2024-09-16 19:34 UTC, RylieWeaver commented
@allaffa I seem to be getting an error relating to dataset creation on GitHub. Have you ever seen something like this before?

2024-09-17 19:23 UTC, allaffa commented on examples/LennardJones/distributed_utils.py
> +def nsplit(a, n):
@RylieWeaver 
This function is already included inside "hydragnn/utils/distributed.py"
Import it from there without re-implementing it.

2024-09-17 19:26 UTC, allaffa commented on examples/LennardJones/graph_utils.py
> +import torch
@RylieWeaver 
These functions are already implemented in `hydragnn/preprocess/utils.py`
Can you use those implementations or did you make any changes?

2024-09-17 19:52 UTC, allaffa requested changes
@RylieWeaver 
Additional changes that you forgot to address in the preview review of the PR

2024-09-17 20:48 UTC, allaffa commented on examples/LennardJones/LJ_inference_plots.py
> +# Copyright (c) 2021, Oak Ridge National Laboratory                          #
```suggestion
# Copyright (c) 2024, Oak Ridge National Laboratory                          #
```

2024-09-17 20:50 UTC, allaffa approved these changes
@RylieWeaver 
I committed just one tiny change on the year of the Copyright.

2024-09-17 21:05 UTC, RylieWeaver commented
> @RylieWeaver I committed just one tiny change on the year of the Copyright.

@allaffa Ok, cool, I just did a couple of cleanup things as well but it should pass all tests again.

2024-09-18 02:23 UTC, allaffa approved these changes

2024-09-18 02:25 UTC, allaffa commented
@pzhanggit @jychoi-hpc 
I have been working with Rylie on this PR for quite some time. 
Even if nominally all commits are authored by him, some portions of code were written by me in local script that I passed to him. 
Because of this, sine I have been heavily involved in the code development of this PR, I would appreciate the opinion of fresh eyes, since you may catch issues or concerns in terms of software design that I have not caught myself.

2024-09-19 14:02 UTC, RylieWeaver commented
Double-clicking on this, let me know what you think @pzhanggit @jychoi-hpc 

There are some more PRs in waiting that require this one first, so I'd like to get this one approved or revised soon if possible. Thanks.

2024-09-19 14:52 UTC, allaffa commented
> Double-clicking on this, let me know what you think @pzhanggit @jychoi-hpc
> 
> There are some more PRs in waiting that require this one first, so I'd like to get this one approved or revised soon if possible. Thanks.

@pzhanggit and @jychoi-hpc 

For the interest of time, please focus only on reviewing only the files that change the core capabilities of hydragnn:

- `hydragnn/models/Base.py`
- `hydragnn/train/train_validate_test.py`

All the other files are in the "examples" folder, therefore they do no affect the core of HydraGNN. The reason why I asked for you to review the PR is because of the two files above.

2024-09-19 18:59 UTC, jychoi-hpc approved these changes
Thank you for the update. I looked over the base and train script. It looks good to me.

2024-09-19 20:25 UTC, RylieWeaver commented on hydragnn/models/Base.py
> +        )[0].float()
Here's my understanding of it: 
The `grad_outputs` argument essentially serves as a weight to multiply the gradients. This is necessary since `graph_energy_pred` is a higher dimension than just a scalar. The _torch.ones_like()_ here will assign a weight of 1 to each gradient, which I believe is what we want. Otherwise, there would be a force prediction which is c*grad_E where c is a constant not equal to 1, which is nonphysical.

Specifically to your question:
No, I don't believe that it results in a sum. The output shape of forces_pred will be in the same shape as data.pos. The grad_outputs specifically is for weighting the gradients before a sum, but that extra step of summing is outside of autograd calculation I believe.

Does this answer your question?

2024-09-19 20:45 UTC, pzhanggit commented on hydragnn/models/Base.py
> +        )[0].float()
> I don't think so.
> 
> Here's my understanding of it: The `grad_outputs` argument essentially serves as a weight to multiply the gradients. This is necessary since `graph_energy_pred` is a higher dimension than just a scalar. The _torch.ones_like()_ here will assign a weight of 1 to each gradient, which I believe is what we want. Otherwise, there would be a force prediction which is c*grad_E where c is a constant not equal to 1, which is nonphysical.
> 
> Specifically to your question: No, I don't believe that it results in a sum. The output shape of forces_pred will be in the same shape as data.pos. The grad_outputs specifically is for weighting the gradients before a sum, but that extra step of summing is outside of autograd calculation I believe.
> 
> Does this answer your question?
> 
> @pzhanggit

Thanks. So just to verify if my understanding is correct: `grad_outputs` is needed because we're calculating gradients of a batch of samples here. And since `grad_outputs should be a sequence of length matching output containing the “vector” in vector-Jacobian product`, it provides a way to aggregate/sum the gradients across all the samples in the batch. This is equivalent to calculate the gradients iteratively for each sample, since the cross-gradients between samples would be zero.

2024-09-19 21:08 UTC, RylieWeaver commented on hydragnn/models/Base.py
> +        )[0].float()
@pzhanggit 

>> grad_outputs is needed because we're calculating gradients of a batch of samples here
Yep, that's right.

>> And since grad_outputs should be a sequence of length matching output containing the “vector” in vector-Jacobian product
I think so. Yes, `grad_outputs` should be a sequence, and it should be the same shape as whatever you're predicting. It then multiplies the matrix of gradients (row-wise, not normal matrix multiplication), which I think is the `vector-Jacobian product` you're referring to.

>> it provides a way to aggregate/sum the gradients across all the samples in the batch. 
I think yes. It's scaling those gradients, which would be relevant in an aggregation/sum. Although, it does not do that aggregation/sum.

>> This is equivalent to calculate the gradients iteratively for each sample, since the cross-gradients between samples would be zero.
Yep.

Are there any parts still unclear?

2024-09-19 21:12 UTC, pzhanggit commented on hydragnn/models/Base.py
> +        )[0].float()
> @pzhanggit
> 
> > > grad_outputs is needed because we're calculating gradients of a batch of samples here
> 
> Yep, that's right.
> 
> > > And since grad_outputs should be a sequence of length matching output containing the “vector” in vector-Jacobian product
> 
> I think so. Yes, `grad_outputs` should be a sequence, and it should be the same shape as whatever you're predicting. It then multiplies the matrix of gradients (row-wise, not normal matrix multiplication), which I think is the `vector-Jacobian product` you're referring to.
> 
> > > it provides a way to aggregate/sum the gradients across all the samples in the batch.
> 
> I think yes. It's scaling those gradients, which would be relevant in an aggregation/sum. Although, it does not do that aggregation/sum.
> 
> > > This is equivalent to calculate the gradients iteratively for each sample, since the cross-gradients between samples would be zero.
> 
> Yep.
> 
> Are there any parts still unclear?

`Scaling those gradients`?

2024-09-19 21:32 UTC, allaffa commented on hydragnn/models/Base.py
> +        )[0].float()
The scaling is done with `torch.ones_like(graph_energy_pred)`
In our case, we use vectors of ones because we do NOT want to scale. However, you could apply any multiplying factor (or even provide a customized vector with different values for each entry).

2024-09-19 21:39 UTC, RylieWeaver commented on hydragnn/models/Base.py
> +        )[0].float()
@pzhanggit @allaffa ^ on what Max said. Also, feel free to @ me so In reply faster :)

2024-09-19 21:53 UTC, RylieWeaver commented on hydragnn/models/Base.py
> +        )[0].float()
Yep. Wow, the o1-preview is great

2024-09-20 00:11 UTC, pzhanggit approved these changes

2024-09-20 00:11 UTC, pzhanggit commented on hydragnn/models/Base.py
> +        )[0].float()
thanks.

2024-09-20 00:20 UTC, merged