MACE
ORNL/HydraGNN pull request #287
Opened 2024-09-25 15:02 UTC by RylieWeaver

An implementation of the MACE Model in HYDRA.

There are 2 key aspects of the MACE Architecture:
(1) Message passing and interaction blocks are equivariant to the O(3) (rotation/inversion) group and invariant to the T(3) (translation) group.
(2) Predictions are made in an n-body expansion, where n is the number of layers. This is done by creating multi-body interactions, then decoding them. Layer 1 will decode 1-body interactions, layer 2 will decode w-body interactions, and so on. So, for a 3-layer model predicting energy, there are 3 outputs for energy, one at each layer, and they are summed at the end. This requires some adjustment to the behavior from Base.py. Specifically, there is a multihead decoder adapted from HYDRA after each convolutional layer.

2024-09-25 15:07 UTC, allaffa commented on .vscode/.vscode/launch.json
> +{
@RylieWeaver 
Is this file really needed or has it been added inadvertently?

2024-09-25 15:08 UTC, allaffa commented on .vscode/launch.json
> +{
@RylieWeaver 
Is this file really needed or has it been added inadvertently?

2024-09-25 15:08 UTC, allaffa commented on examples/qm9/qm9.json
> +            "model_type": "MACE",
@RylieWeaver 
Have the changes to QM9 been added inadvertently?
Why are you changing existing examples?

2024-09-25 15:10 UTC, allaffa requested changes
Some files may have been added or changes by mistake. 
Please check and explain.

2024-09-25 15:13 UTC, RylieWeaver commented on examples/qm9/qm9.json
> +            "model_type": "MACE",
@allaffa In all 3 of these files, they are inadvertent. Generally I clean these up later because if I fail the GitHub tests, then I still have the changes related to debugging.

If it's better, I can ping you when cleaned for review, but in general if you see something weird you are probably correct and it'll be removed later.

2024-09-25 18:59 UTC, RylieWeaver commented
@allaffa As you can see, the MACE repo had a large collection of utils files. I'd like your opinion on how to handle these. On one hand, leaving too much can create clutter. On the other hand, taking things out could reduce customization options / induce unforeseen errors later on.

I think there is a middle-ground, where I could take out ~50% of the utils, focusing on dataset/distributed utils. In terms of impact, I estimate that it would only make a difference to a curious MACE user that uses an unusual argument, since it's hard to account for all these when cleaning out a big repo. In terms of time, it would take a day or two so still be ready by Monday to rebase.

2024-09-25 19:05 UTC, RylieWeaver commented
@allaffa Additionally, despite having torch in their name, I have place `torch-ema` and `torchmetrics` in `requirements.txt`. I did this because the index-url for requirements-torch.txt was incompatible with thos packages. Is there a more preferable way to do this, or this is fine?

2024-09-25 19:38 UTC, allaffa commented on hydragnn/utils/mace_utils/data/hdf5_dataset.py
> +class HDF5Dataset(Dataset):
@RylieWeaver 
here we will definitely need to interact with @jychoi-hpc to make sure that this dataset class interfaces well with the existing dataset infrastructure.

2024-09-25 19:39 UTC, allaffa commented on hydragnn/utils/mace_utils/data/neighborhood.py
> +from typing import Optional, Tuple
@RylieWeaver 
What new capabilities does this add on top of the existing RadiusGraphPBC ?

2024-09-25 19:41 UTC, allaffa commented on hydragnn/utils/mace_utils/data/utils.py
> +###########################################################################################
@RylieWeaver 
I see that these capabilities try to ensure compatibility between our implementation of MACE with the existing standalone open source implementation. 
However, is there any way to actually test the similarity between the two implementations? unless we have specific datasets to test this, it seems like this utils are somewhat dead-ended.

2024-09-25 19:42 UTC, allaffa commented on hydragnn/utils/mace_utils/modules/irreps_tools.py
> +###########################################################################################
@RylieWeaver 
Do you think these utils are MACE-specific or can they be interchangeably used also for other equivariant models, namely NequIP?

2024-09-25 19:49 UTC, allaffa commented on hydragnn/utils/mace_utils/modules/models.py
> +###########################################################################################
@RylieWeaver 
This seems to be the native MACE implementation that we support as an isolated standalone set of scripts, correct? In this case, we could expand a bit further the comments at the top of the file to make this intention more explicit. For instance, we could explicitly mention the hyperlink to the files (mentioning also date and time we looked at those files, so that if those files change in the future, people know when to look back in the repository history). This could help especially in the perspective that the MACE developer may take a look at our code, as we did with theirs :)
It would be nice to come up with examples/scripts that can test the mathematical equivalence between this native implementation and our own integrated in the HydragNN framework.

2024-09-25 19:51 UTC, allaffa commented on hydragnn/utils/mace_utils/modules/models.py
> +class EnergyDipolesMACE(torch.nn.Module):
@RylieWeaver 
why is this model different from the regular MACE? why does it not inherit from the MACE class itself?

2024-09-25 19:54 UTC, allaffa commented on hydragnn/utils/mace_utils/modules/radial.py
> +###########################################################################################
@RylieWeaver 
Similarly to what asked for the `o3.irrep` functionalities, do these functionalities for Bessel function need to be MACE-specific or can they be made available also for other models. For instance, `DimeNet++` uses Bessel functions too [DmeNet++](https://github.com/ORNL/HydraGNN/blob/main/hydragnn/models/DIMEStack.py).
Can we make one implementation available for multiple models?

2024-09-25 19:55 UTC, allaffa commented on hydragnn/utils/mace_utils/modules/symmetric_contraction.py
> +###########################################################################################
@RylieWeaver 
Are also these functionalities MACE-specific or can they be made available for multiple models?

2024-09-25 19:57 UTC, allaffa commented on hydragnn/utils/mace_utils/tools/cg.py
> +###########################################################################################
@RylieWeaver 
Are also the functionalities for the Clebsch Gordan inner product MACE-specific or could they help support the implementation of other model?

2024-09-25 20:00 UTC, allaffa commented on hydragnn/utils/mace_utils/tools/scatter.py
> +"""basic scatter_sum operations from torch_scatter from
@RylieWeaver 
Are these implementations different from what the package `torch-scatter` natively provides?
Please take a look at this [torch-scatter](https://github.com/rusty1s/pytorch_scatter/blob/master/csrc/scatter.cpp)

2024-09-25 20:02 UTC, allaffa commented on hydragnn/utils/mace_utils/tools/torch_geometric/batch.py
> +from collections.abc import Sequence
@RylieWeaver 
Do we need this as standalone routine instead of using the native implementation provided by `torch-geometric`?

2024-09-25 20:02 UTC, allaffa requested changes
Second round of review completed.

2024-09-25 20:04 UTC, RylieWeaver commented on hydragnn/utils/mace_utils/tools/torch_geometric/batch.py
> +from collections.abc import Sequence
@allaffa Want to meet on Teams to discuss?

2024-09-26 02:34 UTC, allaffa commented on hydragnn/utils/config_utils.py
> +    edge_models = ["PNAPlus", "PNA", "CGCNN", "SchNet", "EGNN", "MACE"]
@RylieWeaver 
Could we add also `DimeNet++` to this list?

2024-09-26 02:34 UTC, allaffa commented on hydragnn/utils/config_utils.py
> +        ), "Edge features can only be used with MACE, EGNN, SchNet, PNA, PNAPlus, and CGCNN."
@RylieWeaver 
Could we add also `DimeNet++` to this list?

2024-09-26 02:35 UTC, allaffa reviewed
Just a coupled of questions about why `DimeNet++` is missing from some tests

2024-09-26 14:26 UTC, RylieWeaver commented on hydragnn/utils/config_utils.py
> +    edge_models = ["PNAPlus", "PNA", "CGCNN", "SchNet", "EGNN", "MACE"]
Hmm, double-checking that DImeNet supports edge feats...

2024-09-26 14:37 UTC, RylieWeaver commented on hydragnn/utils/config_utils.py
> +    edge_models = ["PNAPlus", "PNA", "CGCNN", "SchNet", "EGNN", "MACE"]
@allaffa DimeNet's architecture doesn't natively support edge_feats. It would be possible to customize the `InteractionPPBlock` to do it (~1 days work) if it's of interest. However, it would not be the original architecture.

2024-09-26 21:28 UTC, RylieWeaver commented
@allaffa 

There is something important to note wrt `blocks.py` in MACE:

Many of these blocks need to be changed in order to adapt to HYDRA (usually shaping and variable passing).  Importantly, many of these "blocks" are similar, with small tweaks. For example:
```
    RealAgnosticAttResidualInteractionBlock,
    RealAgnosticInteractionBlock,
    RealAgnosticResidualInteractionBlock,
    ResidualElementDependentInteractionBlock,
```

The differences between these blocks are a residual connection or not, and similarly small adjustments. Given the similarities and in order to make it more tractable, I chose to adjust and implement one of these blocks, which I discern to be generally applicable and effective. For example, I chose `RealAgnosticAttResidualInteractionBlock` out of those 4.

TLDR: This should be generally effective to choose one block and move forward, however is important to note down to memory in case an impassioned MACE user comes around with a very specific choice of architecture.

2024-09-26 21:42 UTC, allaffa commented
> @allaffa
> 
> There is something important to note wrt `blocks.py` in MACE:
> 
> Many of these blocks need to be changed in order to adapt to HYDRA (usually shaping and variable passing). Importantly, many of these "blocks" are similar, with small tweaks. For example:
> 
> ```
>     RealAgnosticAttResidualInteractionBlock,
>     RealAgnosticInteractionBlock,
>     RealAgnosticResidualInteractionBlock,
>     ResidualElementDependentInteractionBlock,
> ```
> 
> The differences between these blocks are a residual connection or not, and similarly small adjustments. Given the similarities and in order to make it more tractable, I chose to adjust and implement one of these blocks, which I discern to be generally applicable and effective. For example, I chose `RealAgnosticAttResidualInteractionBlock` out of those 4.
> 
> TLDR: This should be generally effective to choose one block and move forward, however is important to note down to memory in case an impassioned MACE user comes around with a very specific choice of architecture.

@RylieWeaver 
I agree with your choice and thank you for letting me know.

2024-09-27 19:48 UTC, RylieWeaver commented
@allaffa Here are the main updates on MACE:

Progress: 
(1) It is rebased to the recent utils PR
(2) Almost all the low-hanging fruit to delete has been taken out

Next Steps:
(1) Investigate unnecessary or broadly applicable functions. For example, `scatter_add` might be importable from torch_scatter, and `cg.py` might have things used in Nequip.
(2) Fix `data.x` use. Although the tests are passing, the one-hot encoding I apply could cause errors in general cases. This will be changed, although it's worth noting it's **highly recommended** that node features like atom type are one-hot-encoded when input to MACE. I'll put this in a comment and `RaiseWarning` somewhere

Notes:
(1) I've changed a lot of the test/json files just so it runs faster, but I'll revert these before the final draft.
(2) Re: It's highly recommended that node_features like atom type are one-hot encoded when input into MACE

2024-09-28 04:17 UTC, allaffa commented on hydragnn/utils/model/mace_utils/modules/irreps_tools.py
> +###########################################################################################
@RylieWeaver 
Specify from which source you got this file

2024-09-28 04:18 UTC, allaffa commented on hydragnn/utils/model/mace_utils/modules/blocks.py
> +###########################################################################################
@RylieWeaver 
Specify form which source you got this file.

2024-09-28 04:19 UTC, allaffa commented on hydragnn/utils/model/mace_utils/modules/radial.py
> +###########################################################################################
@RylieWeaver 
Specify from which source you got this file.

2024-09-28 04:19 UTC, allaffa commented on hydragnn/utils/model/mace_utils/modules/symmetric_contraction.py
> +###########################################################################################
@RylieWeaver 
Specify from which source you got this file.

2024-09-28 04:19 UTC, allaffa commented on hydragnn/utils/model/mace_utils/modules/utils.py
> +###########################################################################################
@RylieWeaver 
Specify from which source you got this file.

2024-09-28 04:20 UTC, allaffa commented on hydragnn/utils/model/mace_utils/tools/cg.py
> +###########################################################################################
@RylieWeaver 
Specify from which source you got this file.

2024-09-28 04:21 UTC, allaffa commented on hydragnn/utils/model/mace_utils/tools/scatter.py
> +"""basic scatter_sum operations from torch_scatter from
@RylieWeaver 
Remember to check if these functionalities are already provided in the new versions of the package `torch-scatter `

2024-09-28 04:22 UTC, allaffa commented on tests/test_graphs.py
> +        # "SAGE",
@RylieWeaver 
You commented all the other models out. I guess this is one for now since the pR is in draft mode. However, remember to uncomment them as soon as the PR needs to be ready for review.

2024-09-28 04:23 UTC, allaffa commented on tests/test_graphs.py
> +    # "model_type", ["PNA", "PNAPlus", "CGCNN", "SchNet", "EGNN", "MACE"]
@RylieWeaver 
You commented all the other models out. I guess this is one for now since the pR is in draft mode. However, remember to uncomment them as soon as the PR needs to be ready for review.

2024-09-28 04:23 UTC, allaffa commented on tests/test_graphs.py
> +# @pytest.mark.parametrize(
@RylieWeaver 
You commented all the other models out. I guess this is one for now since the pR is in draft mode. However, remember to uncomment them as soon as the PR needs to be ready for review.

2024-09-28 04:23 UTC, allaffa reviewed
A few additional comments left.

2024-09-30 17:33 UTC, RylieWeaver commented on hydragnn/utils/model/mace_utils/modules/utils.py
> +###########################################################################################
Should it have more than this?:

```
###########################################################################################
# Utilities
# Authors: Ilyes Batatia, Gregor Simm and David Kovacs
# This program is distributed under the MIT License (see MIT.md)
###########################################################################################
```

2024-09-30 17:34 UTC, RylieWeaver commented on hydragnn/utils/model/mace_utils/modules/utils.py
> +###########################################################################################
Do you just mean to link it?

2024-09-30 17:37 UTC, RylieWeaver commented on hydragnn/utils/mace_utils/modules/models.py
> +class EnergyDipolesMACE(torch.nn.Module):
MACE has a bunch of models that are slightly different for different applications. I took this one out and others, and kept the general-case MACE.

2024-09-30 17:37 UTC, RylieWeaver commented on hydragnn/utils/mace_utils/data/hdf5_dataset.py
> +class HDF5Dataset(Dataset):
Unnecessary deletion

2024-09-30 17:37 UTC, RylieWeaver commented on hydragnn/utils/mace_utils/data/neighborhood.py
> +from typing import Optional, Tuple
Unnecessary Deletion

2024-09-30 17:38 UTC, RylieWeaver commented on hydragnn/utils/mace_utils/data/utils.py
> +###########################################################################################
Unnecessary Deletion

2024-09-30 18:28 UTC, RylieWeaver commented on hydragnn/utils/mace_utils/tools/torch_geometric/batch.py
> +from collections.abc import Sequence
Unnecessary Deletion

2024-09-30 18:33 UTC, allaffa commented on hydragnn/utils/model/mace_utils/tools/cg.py
> +###########################################################################################
@RylieWeaver 
In the last meeting, we had discussed the idea of including the hyperlink in the description long with the date on which the file has been taken from the original repo. This way, if the file is changed later, people can revert to the version that we took ourselves.

2024-09-30 18:37 UTC, RylieWeaver commented on hydragnn/utils/model/mace_utils/tools/cg.py
> +###########################################################################################
@allaffa Ah, I see now. I had this in `MACESTACK.py` interpreted this as sufficient, but can add this to the other files.

2024-09-30 18:55 UTC, allaffa commented on hydragnn/utils/model/mace_utils/modules/__init__.py
> +# Taken From:
@RylieWeaver 
Yes, I like this. Please apply to all the other files as well.

2024-09-30 18:55 UTC, allaffa reviewed
Getting closer. :)

2024-09-30 19:20 UTC, RylieWeaver commented
@allaffa 

> Getting closer. :)

Yep :). Here’s a summary update for posterity, which I’ll also cover in the meeting:

---

1. Replacing `torch_scatter` operations with an import worked fine. The original implementation avoided it for dependency reasons, but we’re good as long as we can install `torch_scatter`.

2. I moved `irreps_tools.py` to the `utils/model` directory for broader applicability and created `operations.py` for a general function to get `edge_vectors_and_lengths`. We might revisit the naming or location.

3. I couldn’t find anything similar in Nequip to generalize further. For example, `grep` searches for "wigner," "U_matrix," and "Contraction" returned nothing. Nequip's `InteractionBlock` is also different.

4. In `compile.py`, I left all compilation-related functions to ensure speed and accuracy, even though some can be commented out without issue.

2024-09-30 19:23 UTC, RylieWeaver commented
@allaffa At this point, I have made all changes which I can think of. So, I think the steps left are:

(1) Review by you, making any changes requested
(2) Revert the changes I made to json and test_***.py files for quicker testing
(3) Last review by you and Pei
(4) Merge

2024-10-01 16:35 UTC, RylieWeaver commented
@allaffa 

There is an important update to note here which I've realized. It is that **_MACE only natively supports atomic_numbers as node_attributes_**. I am following up with the author, but I believe it is unfeasible or non-trivial or to change this.

At the current version that I have pushed now, it is a requirement that only raw atomic numbers are passed as node_attributes. I do the one-hot encoding automatically.

I also include tests in `process_node_attributes` function of `MACEStack.py` which will warn or throw an error if the data looks off.

2024-10-02 16:40 UTC, allaffa commented on hydragnn/utils/model/mace_utils/modules/blocks.py
> +@compile_mode("script")
@RylieWeaver 
Add a comment line above this function to explain that the original MACE had also different alternative interactions blocks. We should explain that this is only one of the many interaction blocks available, and that the other blocks can be retrieved from the original MACE implementation.

2024-10-02 16:43 UTC, allaffa commented on hydragnn/utils/model/mace_utils/modules/radial.py
> +
@RylieWeaver 
Is this applied to avoid abrupt cutoff of the interactions and therefore ensure differentiability? 
If my understanding is right, please add a few sentences on top to of this function to explain this.

2024-10-02 16:44 UTC, allaffa commented on hydragnn/utils/model/mace_utils/modules/radial.py
> +class ZBLBasis(torch.nn.Module):
@RylieWeaver 
is this used currently? Do you foresee the need to use it in the future? if yes, why?

2024-10-02 16:47 UTC, allaffa commented on hydragnn/utils/model/operations.py
> +##############################################################################
@RylieWeaver 
What do you think about including this function into [hydragnn/preprocess/graph_samples_checks_and_updates.py](https://github.com/ORNL/HydraGNN/blob/main/hydragnn/preprocess/graph_samples_checks_and_updates.py)?

2024-10-02 16:51 UTC, allaffa reviewed
One more round of review completed.

2024-10-02 18:18 UTC, RylieWeaver commented on hydragnn/utils/model/mace_utils/modules/radial.py
> +
@allaffa 

No, that is done outside of the specific basis type. Specifically, the RadialEmbeddingBlock has these lines:

```
        if radial_type == "bessel":
            self.bessel_fn = BesselBasis(r_max=r_max, num_basis=num_bessel)
        elif radial_type == "gaussian":
            self.bessel_fn = GaussianBasis(r_max=r_max, num_basis=num_bessel)
        elif radial_type == "chebyshev":
            self.bessel_fn = ChebychevBasis(r_max=r_max, num_basis=num_bessel)
        if distance_transform == "Agnesi":
            self.distance_transform = AgnesiTransform()
        elif distance_transform == "Soft":
            self.distance_transform = SoftTransform()
        self.cutoff_fn = PolynomialCutoff(r_max=r_max, p=num_polynomial_cutoff)
```

```
return radial * cutoff
```

So, the cutoff is applied outside of the exact type of radial function. These specific lines perform the Gaussian Smearing for radial basis function, where the `self.gaussian_weights` are the gaussian centers.

2024-10-02 18:31 UTC, RylieWeaver commented on hydragnn/utils/model/mace_utils/modules/radial.py
> +class AgnesiTransform(torch.nn.Module):
@allaffa 

Not regularly that I have seen. Similar to the ZBLBasis, it serves as just another hyperparameter for the way to transform and use distance.

2024-10-02 18:52 UTC, RylieWeaver commented on hydragnn/utils/model/operations.py
> +##############################################################################
@allaffa 

Hmm, I am unsure. If we move it into the `preprocess` directory, would we want to execute it during the preprocess steps, rather than during `_conv_args` function? That would make strict sense, but would be slightly more complicated. How do you think it would look in this way?

2024-10-02 19:36 UTC, RylieWeaver commented on requirements-torch2.txt
> +e3nn
@allaffa

Ok, I have changed it so that they are all in `requirement-torch.txt`. This requires 2 things:

(1) An additional url to be passed to the pip install in `CI.yml`. This is where the pip install looks if it can't find the package in the first url.
(2) The specific package version to be specified. This way, an outdated package does not get found and installed from the first url.

2024-10-02 19:37 UTC, RylieWeaver commented
Ready for next round of review

2024-10-03 16:04 UTC, allaffa commented on hydragnn/utils/config_utils.py
> +    edge_models = ["PNAPlus", "PNA", "CGCNN", "SchNet", "EGNN", "MACE"]
@RylieWeaver 
Would it be ok to include this option in DimeNet++? Obviously this would be addressed in a separate PR, not this one.

2024-10-03 16:08 UTC, allaffa commented
> @allaffa
> 
> > Getting closer. :)
> 
> Yep :). Here’s a summary update for posterity, which I’ll also cover in the meeting:
> 
> 1. Replacing `torch_scatter` operations with an import worked fine. The original implementation avoided it for dependency reasons, but we’re good as long as we can install `torch_scatter`.
> 2. I moved `irreps_tools.py` to the `utils/model` directory for broader applicability and created `operations.py` for a general function to get `edge_vectors_and_lengths`. We might revisit the naming or location.
> 3. I couldn’t find anything similar in Nequip to generalize further. For example, `grep` searches for "wigner," "U_matrix," and "Contraction" returned nothing. Nequip's `InteractionBlock` is also different.
> 4. In `compile.py`, I left all compilation-related functions to ensure speed and accuracy, even though some can be commented out without issue.

@RylieWeaver 
Since  the functionalities in`compile.py` can be commented out without issue and are provided only for the sake of speed-up, I think it would be beneficial to add a short description about this at the beginning of the file.

2024-10-03 16:08 UTC, allaffa reviewed
I left a few more comments.

2024-10-03 16:25 UTC, RylieWeaver commented on hydragnn/utils/config_utils.py
> +    edge_models = ["PNAPlus", "PNA", "CGCNN", "SchNet", "EGNN", "MACE"]
@allaffa 
So, adjust DimeNet to allow for edge_feats? Yes, I could do this and put it on my to-do. Just like the message to confirm.

2024-10-03 16:41 UTC, allaffa commented on hydragnn/utils/model/operations.py
> +##############################################################################
I see what you mean. Let us keep it as is.

2024-10-03 16:43 UTC, allaffa commented on hydragnn/utils/model/mace_utils/modules/radial.py
> +class AgnesiTransform(torch.nn.Module):
@RylieWeaver 
If we keep it as an alternatively option, then we should create a test which is regularly run by the CI where these bases are used. This is the only way to check that these functionalities will not be broken by future changes in the repository. 
Keeping these things hanging around without actually using them is very risky and prone to having things around that will easily become deprecated and not supported anymore.

2024-10-03 16:43 UTC, allaffa reviewed
Another round completed.

2024-10-03 16:48 UTC, allaffa commented on hydragnn/utils/model/mace_utils/modules/radial.py
> +class ZBLBasis(torch.nn.Module):
@RylieWeaver 
I would add a comment to the file saying that this basis is useful for modeling extremely close interactions, where nuclear forces dominate ([https://arxiv.org/abs/1904.00360]).

Also, I think we should have a dedicated test in the CI where we continuously check that the MACE model can switch between different choice of basis functions, so that we make sure that these basis are maintained in our code and their use does not become deprecated.

2024-10-04 20:53 UTC, RylieWeaver commented on hydragnn/utils/model/mace_utils/modules/radial.py
> +class ZBLBasis(torch.nn.Module):
@allaffa 

(1) After further looking into it, I believe I was partially mistaken on the ZBL basis. It is useful for modeling close interactions, but is for predicting atomic energies, not serving as a distance transformation. Given that Hydra is application-agnostic and the niche use-case, I believe it should just be removed.

(2) I made a new test file `test_radial_transforms.py` to test all the different possible transformations. In the future, other models with multiple possible transformations could be put in here as well. Let me know if this is what you're thinking, or if another way is better.

2024-10-08 15:41 UTC, allaffa commented on tests/test_graphs.py
> +        # "GIN",
@RylieWeaver 
You MUST absolutely get rid of this comments once for all. 
 "temporarily" commenting things out like this is extremely dangerous.

2024-10-08 15:42 UTC, allaffa commented on tests/test_graphs.py
> +#     "model_type",
@RylieWeaver 
Uncomment what needs to be kept, and remove everything else.

2024-10-08 15:42 UTC, allaffa reviewed
Another round of review

2024-10-08 21:43 UTC, RylieWeaver commented
@allaffa 

Ready for next round. All tests should be running now.

2024-10-08 21:56 UTC, allaffa commented
@RylieWeaver 
Conflicts left to resolve

2024-10-08 22:30 UTC, RylieWeaver commented
> @RylieWeaver Conflicts left to resolve

Oh, it's from the typo fix just now. The struggle of multiple PRs, lol

2024-10-09 00:20 UTC, allaffa commented on tests/test_radial_transforms.py
> +torch.manual_seed(97)
@RylieWeaver 
Is there any reason why you chose 97 ?

2024-10-09 00:24 UTC, allaffa approved these changes
I left just a question about the torch seed set to 97. 
For the rest, it looks good to me.

2024-10-09 13:42 UTC, RylieWeaver commented on tests/test_radial_transforms.py
> +torch.manual_seed(97)
@allaffa 

Nope, this is just an artifact of me using the code from `test_graphs.py` to make this test.

2024-10-09 13:44 UTC, RylieWeaver commented
> I left just a question about the torch seed set to 97. For the rest, it looks good to me.

Shall we have Pei take a look for a final check with some fresh eyes?

2024-10-15 00:00 UTC, ArCho48 approved these changes

2024-10-15 01:02 UTC, merged