WIP Add QM9 example with torch dataset
ORNL/HydraGNN pull request #35
Opened 2021-11-19 15:11 UTC by streeve

2021-11-21 18:25 UTC, allaffa commented
@streeve 

Thank you for doing this. 
What I have in mind is to provide the users with examples of simple, intermediate, and advanced difficulty. 

**Simple**: use datasets directly provided in` torch.geometric` and explicitly build the NN without configure files and without using `hydrogen/models/create.py `
**Intermediate**: use datasets directly provided in `torch.geometric` and explicitly build the NN using configure files that are passed to `hydrogen/models/create.py `
**Advanced**: use personalized datasets directly provided by raw data files and explicitly build the NN using configure files that are passed to `hydrogen/models/create.py `

Some of the **simple** examples (those ones that can be run in a reasonably short amount of time) would also be good candidates to become unit tests. 

What you provide is a very good **intermediate**.

2021-11-22 17:59 UTC, streeve commented
The current issue on this PR is that the PyG QM9 dataset is immutable - we'll have to create a new object to add extra fields for multi-head

2021-11-25 16:36 UTC, allaffa requested changes

2021-11-25 16:36 UTC, allaffa commented on hydragnn/preprocess/serialized_dataset_loader.py
> -    def __update_predicted_values(self, type: list, index: list, data: Data):
@streeve 
Why are you leaving `self.__update_atom_features` as a method of `SerializedDataLoader` and extracting `update_predicted_values` as an external standalone function?

2021-11-29 20:26 UTC, streeve commented
Keeping this open since there are no differences in #42 after rebasing on main

2021-11-29 20:28 UTC, streeve commented on hydragnn/preprocess/serialized_dataset_loader.py
> -    def __update_predicted_values(self, type: list, index: list, data: Data):
I pulled that function out to use it in the new example preprocess functions - which was very easy because it didn't use any class data

2021-11-29 21:01 UTC, streeve commented
@pzhanggit this is up to date with main if you have time to take a look

2021-11-29 22:06 UTC, pzhanggit commented on examples/md17/md17.py
> +arch_config["output_dim"] = [0]
Why is output_dim equal to 0 not 1 for energy?

2021-11-30 16:41 UTC, streeve commented
> Are the codes ready to run?

They still fail on tensor mismatch, but I do not know what the issue is

2021-11-30 17:47 UTC, pzhanggit commented
> > Are the codes ready to run?
> 
> They still fail on tensor mismatch, but I do not know what the issue is
Error message?

2021-11-30 20:49 UTC, streeve commented
For tests to run we either need to update how we install or hack it in for now

2021-12-03 18:09 UTC, streeve commented on examples/md17/md17.py
> +arch_config["output_dim"] = [0]
Seemed reasonable at the time

2021-12-30 22:14 UTC, streeve commented
@jychoi-hpc this seems to be failing in the CI because of the profiler; can you take a look?

2021-12-31 21:57 UTC, jychoi-hpc commented
Sure, I am looking at now.

2022-01-01 02:32 UTC, jychoi-hpc commented
I just made some changes to fix the error with profile:
* replaced "contextlib.nullcontext" with "Profiler()". Now profiler can act as a null.
* update on return values. Replaced `train_rmse, _, _ = train(...)` with `train_rmse, _  = train(...)` as `train()` returns only 2 values.

2022-01-03 16:04 UTC, pzhanggit commented on examples/md17/md17.py
> +arch_config["output_dim"] = [1]
Could we specify this in json input file?

2022-01-04 21:12 UTC, streeve commented
Ran full QM9 dataset for 5 epoch test; looks okay for a start, but needs some work

![Screen Shot 2022-01-04 at 3 10 54 PM](https://user-images.githubusercontent.com/6740307/148124513-e7023276-99b8-4d00-bfdc-202e3b1d89c2.png)

2022-01-11 01:59 UTC, allaffa requested changes

2022-01-11 01:59 UTC, allaffa commented on examples/md17/md17.py
> +    data.y = data.energy / len(data.x)
Why are you dividing the energy by the number of nodes in the graph?

2022-01-11 01:59 UTC, allaffa commented on examples/qm9/qm9.py
> +    data.y = data.y[:, 10] / len(data.x)
Same question as for MD17. Why are you dividing by the size of the graph (i.e., number of nodes)?

2022-01-11 16:55 UTC, streeve commented on examples/md17/md17.py
> +    data.y = data.energy / len(data.x)
This improves the prediction. It's the same unit conversion that Pei added for LSMS, in this case from eV to eV/atom

2022-01-11 16:55 UTC, streeve commented
Updated prediction scaling energy by number of atoms:
![Screen Shot 2022-01-06 at 11 18 49 AM](https://user-images.githubusercontent.com/6740307/148986721-dc839491-919a-40b5-86ef-ec0cf6f1793f.png)

2022-01-11 21:55 UTC, pzhanggit commented on examples/md17/md17.py
> +    data.y = data.energy / len(data.x)
Just curious, for variables in the two datasets, do they have some physical relationships similar to the one in https://github.com/ORNL/HydraGNN/pull/56?

2022-01-11 21:57 UTC, pzhanggit commented
> Updated prediction scaling energy by number of atoms: ![Screen Shot 2022-01-06 at 11 18 49 AM](https://user-images.githubusercontent.com/6740307/148986721-dc839491-919a-40b5-86ef-ec0cf6f1793f.png)

Nice. It seems improved.

2022-01-11 22:02 UTC, pzhanggit commented on examples/md17/md17.py
> +train_loader = DataLoader(train, batch_size=bs, shuffle=False)
Is distributed used in the two examples?

2022-01-11 22:03 UTC, pzhanggit commented on examples/qm9/qm9.py
> +arch_config["output_type"] = ["graph"]
From json file?

2022-01-11 22:07 UTC, pzhanggit commented on hydragnn/preprocess/serialized_dataset_loader.py
> +    data.y_loc = torch.zeros(1, len(type) + 1, dtype=torch.int64)
```suggestion
    data.y_loc = torch.zeros(1, len(type) + 1, dtype=torch.int64, device=data.y.device)
```

2022-01-11 22:08 UTC, pzhanggit commented
It looks alright to me. Only some minor comments

2022-01-12 00:19 UTC, streeve commented on examples/md17/md17.py
> +    data.y = data.energy / len(data.x)
There are a number of thermodynamic variables in the qm9 dataset - right now it's only using free energy. For any of the energetic values I think we will want to change units to energy/atom

2022-01-12 00:27 UTC, streeve commented on examples/qm9/qm9.py
> +arch_config["output_type"] = ["graph"]
Oh, I should use `update_config_NN_outputs`, right? That's why it's not in any other config file. This is confusing as a user :)

2022-01-12 00:27 UTC, streeve commented on hydragnn/preprocess/serialized_dataset_loader.py
> +    data.y_loc = torch.zeros(1, len(type) + 1, dtype=torch.int64)
I'll test on Summit and add any others I missed

2022-01-12 00:29 UTC, streeve commented on examples/md17/md17.py
> +train_loader = DataLoader(train, batch_size=bs, shuffle=False)
Good point - I was lazy and did this here instead of updating the library loading functions

2022-01-19 19:27 UTC, streeve commented on examples/md17/md17.py
> +train_loader = DataLoader(train, batch_size=bs, shuffle=False)
Fixed

2022-01-19 19:27 UTC, streeve commented on examples/qm9/qm9.py
> +arch_config["output_type"] = ["graph"]
Fixed with your update

2022-01-19 19:27 UTC, streeve commented on hydragnn/preprocess/serialized_dataset_loader.py
> +    data.y_loc = torch.zeros(1, len(type) + 1, dtype=torch.int64)
Fixed

2022-01-19 19:28 UTC, streeve commented
@pzhanggit @allaffa can you do a final check?

2022-01-19 20:08 UTC, pzhanggit commented on .github/workflows/CI.yml
> +          export PYTHONPATH=$PYTHONPATH:~/HydraGNN
Thank you

2022-01-19 20:38 UTC, pzhanggit commented on hydragnn/run_training.py
> +    calculate_PNA_degree_config,
No need to add since not used?

2022-01-19 20:41 UTC, pzhanggit approved these changes
Looks great. Thanks!

2022-01-19 21:02 UTC, streeve commented on hydragnn/run_training.py
> +    calculate_PNA_degree_config,
Good point - removed

2022-01-19 21:23 UTC, streeve commented
One more run - I tried increasing the hidden layers. Looks better for sure, but still a bias in the predictions at lower energy

![free_energy](https://user-images.githubusercontent.com/6740307/150215781-ee84226e-2607-4a36-a859-4a956363bc71.png)

2022-01-20 02:49 UTC, allaffa approved these changes

2022-01-20 02:49 UTC, merged