structure examples directority with multuple subdirectories - one per…
ORNL/HydraGNN pull request #37
Opened 2021-11-20 00:51 UTC by allaffa

… example

2021-11-22 16:21 UTC, streeve commented on tests/test_config.py
> +    config_file = os.path.join("examples/dft_lsms", config_file)
Maybe just `lsms` for now? If we expand to examples outside DFT we can add another level to the hierarchy

2021-11-23 00:52 UTC, allaffa commented on tests/test_config.py
> +    config_file = os.path.join("examples/dft_lsms", config_file)
Done.

2021-11-23 14:44 UTC, pzhanggit commented
Need to update example.py file.

2021-11-23 15:08 UTC, pzhanggit approved these changes

2021-11-23 16:22 UTC, pzhanggit commented
> In the QM9 PR I've named `examples/qm9/qm9.json`. I would prefer `lsms/lsms.json` - I assume you disagree :)

Have to reply, lolllll

2021-11-24 00:53 UTC, allaffa commented
> In the QM9 PR I've named `examples/qm9/qm9.json`. I would prefer `lsms/lsms.json` - I assume you disagree :)

Done. I do not know the difference between agreeing and disagreeing anymore. :)

2021-11-29 19:26 UTC, streeve approved these changes

2021-11-29 19:29 UTC, streeve requested changes
Approved, but can you squash these commits?

2021-12-01 02:48 UTC, merged