WIP: Add scaled by num_nodes option for feature prediction in variable graph size
ORNL/HydraGNN pull request #45
Opened 2021-11-29 22:16 UTC by pzhanggit

2021-11-30 16:40 UTC, streeve commented on hydragnn/postprocess/postprocess.py
> +            for isamp in range(len(nodes_num_list)):
`isample`

2021-11-30 16:40 UTC, streeve commented on hydragnn/postprocess/postprocess.py
> +def scaledback_y_data(datasets_list, scaled_index_list, nodes_num_list):
`denormalize_features_num_nodes` or something?

2021-11-30 16:40 UTC, streeve commented on hydragnn/preprocess/raw_dataset_loader.py
> +    def __scaled_features_per_node_update(self, dataset):
Something that matches the free function above

2021-11-30 16:40 UTC, streeve commented on hydragnn/run_training.py
> +            new_state_dict = OrderedDict()
This seems unrelated

2021-11-30 17:51 UTC, pzhanggit commented on hydragnn/postprocess/postprocess.py
> +            for isamp in range(len(nodes_num_list)):
`isamp` is consistent with the function above

2021-11-30 17:53 UTC, pzhanggit commented on hydragnn/postprocess/postprocess.py
> +def scaledback_y_data(datasets_list, scaled_index_list, nodes_num_list):
`scaled_features_by_num_nodes`?

2021-11-30 17:55 UTC, pzhanggit commented on hydragnn/preprocess/raw_dataset_loader.py
> +    def __scaled_features_per_node_update(self, dataset):
`__features_update_scaleddown_num_nodes`?

2021-11-30 17:56 UTC, pzhanggit commented on hydragnn/postprocess/postprocess.py
> +def scaledback_y_data(datasets_list, scaled_index_list, nodes_num_list):
Or `features_scaledup_num_nodes`?

2021-11-30 17:56 UTC, pzhanggit commented on hydragnn/run_training.py
> +            new_state_dict = OrderedDict()
Yeah. This is a bug fix.

2021-11-30 18:19 UTC, streeve requested changes

2021-11-30 18:19 UTC, streeve commented on hydragnn/postprocess/postprocess.py
> +            for isamp in range(len(nodes_num_list)):
I would change them all :)

2021-11-30 18:19 UTC, streeve commented on hydragnn/postprocess/postprocess.py
> +def scaledback_y_data(datasets_list, scaled_index_list, nodes_num_list):
up/down is a little confusing to me. `unscale_features_by_num_nodes`?

2021-11-30 18:19 UTC, streeve commented on hydragnn/preprocess/raw_dataset_loader.py
> +    def __scaled_features_per_node_update(self, dataset):
`__scale_features_by_num_nodes`?

2021-11-30 18:19 UTC, streeve commented on hydragnn/run_training.py
> +            new_state_dict = OrderedDict()
Can you make a separate PR? I also don't understand what this is fixing

2021-12-01 03:25 UTC, allaffa requested changes

2021-12-01 05:23 UTC, pzhanggit commented on hydragnn/postprocess/postprocess.py
> +            for isamp in range(len(nodes_num_list)):
Yes.

2021-12-01 05:33 UTC, pzhanggit commented on hydragnn/run_training.py
> +            new_state_dict = OrderedDict()
Sure, it is supposed to fix model state loading inconsistencies with and without `DistributedDataParallel`. A relevant discussion for example is https://discuss.pytorch.org/t/solved-keyerror-unexpected-key-module-encoder-embedding-weight-in-state-dict/1686. There might be other/better solutions. And you are right it is unrelated to this PR. I am going to move it to a separate PR and we can discuss there.

2021-12-01 05:34 UTC, pzhanggit commented on hydragnn/run_training.py
> +        model.load_state_dict(new_state_dict)
No, it is not needed. I will move it to a separate PR.

2021-12-06 21:58 UTC, streeve commented on hydragnn/utils/model.py
> +    if isinstance(model, torch.nn.parallel.distributed.DistributedDataParallel):
Should rebase out, right?

2021-12-06 21:58 UTC, streeve commented on hydragnn/run_prediction.py
> +            [true_values, predicted_values] = unscale_features_by_num_nodes(
I would generally prefer to still output the predicted energy per node, but I agree that it's important to have this function available. Can we just remove the changes in this file or do you disagree?

2021-12-06 22:06 UTC, pzhanggit commented on hydragnn/run_prediction.py
> +            [true_values, predicted_values] = unscale_features_by_num_nodes(
Either way makes sense to me as long as we know what we are doing. I will remove this piece. What do you think about the one in `train_validate_test.py`?

2021-12-06 22:07 UTC, pzhanggit commented on hydragnn/run_prediction.py
> +            [true_values, predicted_values] = unscale_features_by_num_nodes(
Maybe also remove that one to be consistent?

2021-12-06 22:38 UTC, streeve commented on hydragnn/run_prediction.py
> +            [true_values, predicted_values] = unscale_features_by_num_nodes(
Good point. We can put that code in utils (`unscale_features_by_num_nodes_config`) since you already wrote it

2021-12-06 22:59 UTC, pzhanggit commented on hydragnn/utils/model.py
> +    if isinstance(model, torch.nn.parallel.distributed.DistributedDataParallel):
Done.

2021-12-07 15:35 UTC, streeve commented on hydragnn/run_prediction.py
> +            [true_values, predicted_values] = unscale_features_by_num_nodes(
@pzhanggit I think this is ready once you add the `unscale_features_by_num_nodes_config` function

2021-12-07 15:43 UTC, pzhanggit commented on hydragnn/run_prediction.py
> +            [true_values, predicted_values] = unscale_features_by_num_nodes(
Will do. I misunderstood you and thought you meant to leave it there in `postprocess.py`.

2021-12-07 15:51 UTC, streeve commented on hydragnn/run_prediction.py
> +            [true_values, predicted_values] = unscale_features_by_num_nodes(
Not sure if we're on the same page - I think we should have both `unscale_features_by_num_nodes` and `unscale_features_by_num_nodes_config` in postprocess.py

2021-12-07 15:52 UTC, pzhanggit commented on hydragnn/run_prediction.py
> +            [true_values, predicted_values] = unscale_features_by_num_nodes(
What do you think `unscale_features_by_num_nodes_config` would do?

2021-12-07 15:54 UTC, streeve commented on hydragnn/run_prediction.py
> +            [true_values, predicted_values] = unscale_features_by_num_nodes(
Basically what you just removed from `run_prediction` - check the config options and call `unscale_features_by_num_nodes` as needed

2021-12-07 16:10 UTC, pzhanggit commented on hydragnn/run_prediction.py
> +            [true_values, predicted_values] = unscale_features_by_num_nodes(
@streeve  See d0bd5f30cd54dab5064d1517f81540ca84fb9bf0

2021-12-07 16:14 UTC, streeve approved these changes

2021-12-07 16:14 UTC, streeve commented on hydragnn/postprocess/postprocess.py
> +            "'unscale_features_by_num_nodes_config' should only be used together with 'output_denormalize'",
Good point

2021-12-08 16:10 UTC, merged