Create helper functions
ORNL/HydraGNN pull request #48
Opened 2021-11-30 18:42 UTC by streeve

Moves most of `run_training` and `run_prediction` into separate functions - one step towards moving those to examples rather than in the library. 

Also adds some cases of functions with and without config inputs (always naming the function with a `_config` suffix), trying to make it easy to run either way.

File and function names are certainly up for debate

2021-11-30 22:15 UTC, allaffa requested changes

2021-11-30 22:15 UTC, allaffa commented on hydragnn/models/create.py
> +from hydragnn.utils.distributed import get_device
Thank you for this! It makes much more sense here.

2021-11-30 22:15 UTC, allaffa commented on hydragnn/run_training.py
> +    model = get_distributed_model(model, verbosity)
Thank you for taking care of this. This was long due.

2021-11-30 22:15 UTC, allaffa commented on hydragnn/utils/model.py
> +##############################################################################
Maybe we can name this file "model_utils.py"? 
The word "model" is somewhat misleading, as people may expect to open the file and see the implementation of an actual deep learning model inside.

2021-12-01 15:24 UTC, streeve commented on hydragnn/utils/model.py
> +##############################################################################
I was thinking about this too - only half the files in `utils/` have `_utils` in the name. I see your point, but a user should only need to use `from hydragnn.utils import x`. But I'm okay renaming all with or without `_utils`

2021-12-02 19:06 UTC, streeve commented on hydragnn/utils/model.py
> +##############################################################################
@allaffa @pzhanggit strong feelings on this? I just think we should be consistent on the file names

2021-12-02 22:31 UTC, pzhanggit commented on hydragnn/utils/config_utils.py
> +    var_config = config["NeuralNetwork"]["Variables_of_interest"]
Neat!

2021-12-03 03:32 UTC, allaffa approved these changes

2021-12-03 03:56 UTC, merged