Simplify model creation
ORNL/HydraGNN pull request #50
Opened 2021-12-01 15:40 UTC by streeve

Similar to #48, updating model creation:

- adds version without config input
- separates config input from individual models
- makes inputs only needed for PNA optional

2021-12-02 14:01 UTC, allaffa approved these changes

2021-12-02 14:01 UTC, allaffa commented on hydragnn/models/create.py
> +            output_dim=output_dim,
@streeve 

This is beautiful, as it indeed makes the creation of the mode more practical when the configure file is not needed. For instance, when the data is immediately provided by torch.geometric

2021-12-03 04:31 UTC, pzhanggit commented on hydragnn/models/create.py
> +    dataset: [Data] = None,
Why do we need data in create models?

2021-12-03 04:34 UTC, pzhanggit commented on hydragnn/models/create.py
> +    dataset: [Data] = None,
Just realized PNA needs it for deg. A weak comment: is it better to just pass `deg` here instead of entire dataset?

2021-12-03 04:40 UTC, pzhanggit reviewed
It looks good to me. Only have one minor comment.

2021-12-03 04:50 UTC, allaffa requested changes
Just pass "deg" instead of dataset as suggested already by @pzhanggit

2021-12-03 18:48 UTC, streeve commented
Updated to separate `deg` for PNA, `max_neigh` for MFC, and `num_nodes` for MLP. I squash rebased because things got messy

2021-12-03 19:12 UTC, pzhanggit commented on hydragnn/utils/model.py
> +    num_nodes = dataset[0].num_nodes
This line is not needed?

2021-12-03 19:18 UTC, pzhanggit commented on hydragnn/run_prediction.py
> +    model = create_model_config(
A general comment that is not related to this PR specifically: why do we need to create the model in `run_prediction` (and then load model state )? Could we skip the model creation and just load a trained model directly?

2021-12-03 19:19 UTC, pzhanggit approved these changes
Thanks for the PR. It looks great now.

2021-12-03 20:11 UTC, streeve commented on hydragnn/run_prediction.py
> +    model = create_model_config(
I think we could do that if we save the entire model instead of just the state_dict. Not sure that's worth it

2021-12-03 20:14 UTC, streeve commented on hydragnn/utils/model.py
> +    num_nodes = dataset[0].num_nodes
Fixed

2021-12-03 20:27 UTC, pzhanggit commented on hydragnn/run_prediction.py
> +    model = create_model_config(
Good point, it seems the current way is better and more robust, https://pytorch.org/tutorials/beginner/saving_loading_models.html.

2021-12-03 22:35 UTC, allaffa approved these changes

2021-12-03 22:35 UTC, merged