Adding profiling function
ORNL/HydraGNN pull request #54
Opened 2021-12-04 04:05 UTC by jychoi-hpc

This is a PR for adding profiling routines based on PyTorch's Profiler.

2021-12-05 15:29 UTC, allaffa requested changes

2021-12-05 15:29 UTC, allaffa commented on hydragnn/train/train_validate_test.py
> +    global profile_config_name
@jychoi-hpc is there any easy-fix to avoid the use of global variables?

2021-12-06 22:36 UTC, jychoi-hpc commented on hydragnn/train/train_validate_test.py
> +    global profile_config_name
Let me rewrite the code to remove global variables as much as possible.

2021-12-07 00:14 UTC, jychoi-hpc commented
I have rewritten the code. I added a new class(`Profiler` in `hydragnn/utils/profile.py`) to remove global variables.

2021-12-17 16:10 UTC, streeve reviewed
This is a very nice added capability. I think I understand the basics, but is there any significant performance overhead (either with profiling turned on or off)?

It does make the training loop a little harder to read, but I think that's just the price we pay

2021-12-17 16:10 UTC, streeve commented on hydragnn/train/train_validate_test.py
> +            with record_function("load"):
We'll have to rebase on main - we no longer load here

2021-12-17 17:39 UTC, jychoi-hpc commented on hydragnn/train/train_validate_test.py
> +            with record_function("load"):
Ok. Thank you for pointing this out. I am updating now.

2021-12-19 00:33 UTC, allaffa requested changes

2021-12-19 00:33 UTC, allaffa commented on hydragnn/train/train_validate_test.py
> +    with profiler as prof:
Is there a way to "hide" the action of the profiler so that someone who looks at the implementation of the training loop does not explicitly see the call tot he profile routines?

2021-12-20 15:51 UTC, jychoi-hpc commented on hydragnn/train/train_validate_test.py
> +    with profiler as prof:
Alternatively, we can put the profiler wrapper in one higher up:
```
    for epoch in range(0, num_epoch):
        profiler.set_current_epoch(epoch)
        with profiler as prof:
            train_rmse, train_taskserr = train(
                train_loader, model, optimizer, verbosity, profiler=prof
            )
        val_rmse, val_taskserr = validate(val_loader, model, verbosity)
```
Then, the train function will look like this:
```
def train(...):
    tasks_error = np.zeros(model.num_heads)
    model.train()
    total_error = 0
    for data in iterate_tqdm(loader, verbosity):
        with record_function("zero_grad"):
            opt.zero_grad()
        with record_function("get_head_indices"):
            head_index = get_head_indices(model, data)
        with record_function("forward"):
            pred = model(data)
            loss, tasks_rmse = model.loss_rmse(pred, data.y, head_index)
        with record_function("backward"):
            loss.backward()
        opt.step()
        prof.step()
```

2021-12-20 15:52 UTC, jychoi-hpc commented on hydragnn/train/train_validate_test.py
> +    with profiler as prof:
How do you think?

2021-12-20 16:26 UTC, allaffa commented on hydragnn/train/train_validate_test.py
> +    with profiler as prof:
@streeve @pzhanggit 
Which option do you prefer between the one already implemented and the new one outlined by Jong in this conversation?

2021-12-20 16:29 UTC, allaffa commented on hydragnn/train/train_validate_test.py
> +    with profiler as prof:
@jychoi-hpc 
I personally prefer the new proposed option. Let's see what Sam and Pei think :-)

2021-12-20 17:12 UTC, streeve commented on hydragnn/train/train_validate_test.py
> +    with profiler as prof:
I agree - I think this is ready to merge after the update

2021-12-20 18:12 UTC, jychoi-hpc commented on hydragnn/train/train_validate_test.py
> +    with profiler as prof:
I like the proposed option too. I have updated the code.

2021-12-20 18:39 UTC, streeve commented on hydragnn/train/train_validate_test.py
> +            pred = model(data)
Should we separate the prediction from loss profiling?

2021-12-20 18:39 UTC, streeve approved these changes

2021-12-20 18:45 UTC, allaffa approved these changes

2021-12-20 18:56 UTC, pzhanggit approved these changes

2021-12-20 19:06 UTC, merged