optimize get_head_indices with tensor operations
ORNL/HydraGNN pull request #80
Opened 2021-12-18 21:17 UTC by pzhanggit

Tested on Summit with profiling in https://github.com/ORNL/HydraGNN/pull/54, about 15x speedup is observed

2021-12-20 16:28 UTC, streeve requested changes
It will be great to have this merged! Just requesting name changes, as usual

2021-12-20 16:28 UTC, streeve commented on hydragnn/train/train_validate_test.py
> +    _head_ind = [None] * batch_size
Can we rename this variable to something more clear? Even just something saying it's temporary

2021-12-20 16:28 UTC, streeve commented on hydragnn/train/train_validate_test.py
> +    start_track = sample_start + y_loc[:, :-1]
I don't understand "track". `start_index`?

2021-12-20 16:28 UTC, streeve commented on hydragnn/train/train_validate_test.py
> +    index_pool = torch.arange(0, end_track[-1, -1])
`index_range`?

2021-12-20 16:43 UTC, jychoi-hpc commented
I am just wondering, if we make `head_index` as a torch array on GPU, will it be better? 

It can get some speed up when it used with other tensor data on GPUs, e.g.,:
```
loss, tasks_rmse = model.loss_rmse(pred, data.y, head_index)
```
`pred`, `data.y` are all on GPU, right?

2021-12-20 18:16 UTC, pzhanggit commented
> I am just wondering, if we make `head_index` as a torch array on GPU, will it be better?
> 
> It can get some speed up when it used with other tensor data on GPUs, e.g.,:
> 
> ```
> loss, tasks_rmse = model.loss_rmse(pred, data.y, head_index)
> ```
> 
> `pred`, `data.y` are all on GPU, right?

Good point. Currently it is a list of tenors. `head_index=[tensor_index_head0, tensor_index_head1,...]`.  The thing is that the length of `head_index` for each head is different, for example 32 for `tensor_index_head0` and 32*num_nodes for `tensor_index_head1` when batch_size=32. Not sure how to define a tensor for this, maybe padding? What do you think?
I will make the `tensor_index_head*` on GPU.

2021-12-20 18:25 UTC, jychoi-hpc commented
So, the each element in `head_index` in a tensor (on GPU, if GPU is available). Then, it should be ok with `list`.

2021-12-20 18:32 UTC, pzhanggit commented
> So, the each element in `head_index` in a tensor (on GPU, if GPU is available). Then, it should be ok with `list`.

I will make it so explicitly in a new commit.

2021-12-20 19:20 UTC, streeve commented on hydragnn/train/train_validate_test.py
> +    sample_start = torch.cumsum(total_size, dim=0) - total_size
Along with what @jychoi-hpc was saying, I think you can specify the device (same for `arange`):
`sample_start = torch.cumsum(total_size, dim=0, out=torch.Tensor(device=device))`

2021-12-20 21:24 UTC, pzhanggit commented on hydragnn/train/train_validate_test.py
> +    sample_start = torch.cumsum(total_size, dim=0) - total_size
Yeah, did so. Waiting for nodes on Summit for testing.

2021-12-22 03:01 UTC, pzhanggit commented on hydragnn/train/train_validate_test.py
> +    sample_start = torch.cumsum(total_size, dim=0) - total_size
@streeve  @jychoi-hpc  The tensors should be in the same device with data.x and data.y now.

2021-12-22 16:49 UTC, jychoi-hpc approved these changes
It looks ok to me.

2021-12-30 19:14 UTC, streeve approved these changes
Looks great!

2021-12-30 19:14 UTC, streeve commented on hydragnn/preprocess/serialized_dataset_loader.py
> +            1, len(type) + 1, dtype=torch.int64, device=data.y.device
This is a very nice way to reduce calls to `get_device` and simplify

2021-12-30 19:14 UTC, streeve commented on hydragnn/train/train_validate_test.py
> +    sample_start = torch.cumsum(total_size, dim=0) - total_size
Ok, since you moved `y_loc` to the device, this will default there as well?

2021-12-30 21:21 UTC, pzhanggit commented on hydragnn/train/train_validate_test.py
> +    sample_start = torch.cumsum(total_size, dim=0) - total_size
Yes.

2022-01-03 15:18 UTC, merged