Stratified splitting
ORNL/HydraGNN pull request #81
Opened 2021-12-19 22:24 UTC by allaffa

2021-12-20 17:32 UTC, pzhanggit commented on tests/inputs/ci.json
> +        "stratified_splitting": true,
`stratified_splitting` will not be executed in this test since train/test/val sets are provided separately.

2021-12-20 17:48 UTC, allaffa commented on tests/inputs/ci.json
> +        "stratified_splitting": true,
`stratified_splitting` should be called before the creation of the .pkl files. 

I agree that the unit tests will use the .pkl files once they are created, thus avoiding re-generating the raw data from scratch. But the goal it so stratify the splitting the first time, so that the creation go the p.kl files ensure an equal representation of all the compositions in the training/validate/test portion of the dataset. 

What am I missing?

2021-12-20 18:01 UTC, pzhanggit commented on tests/inputs/ci.json
> +        "stratified_splitting": true,
Nothing is missing. Just a comment `StratifiedShuffleSplit` is not used even though set to be `true` here in the singletask test since the datasets are provided separately in `unittest_train_model`.

2021-12-20 18:16 UTC, allaffa commented on tests/inputs/ci.json
> +        "stratified_splitting": true,
I see...
Do you think it would be good if I added the use of `StratifiedShuffleSplit` inside `unittest_train_model`

2021-12-20 19:15 UTC, allaffa commented on tests/inputs/ci.json
> +        "stratified_splitting": true,
@pzhanggit 
I understand what's happening. What you say is correct. 
I removed the `stratified_splitting` from the `ci.json` configure file

2022-01-03 16:39 UTC, pzhanggit commented on hydragnn/preprocess/load_data.py
> +            category += frequency * (100 ** index)
Is this representation unique? For example, a structure with 4 Fe atoms and 6 Pt atoms would have the same `category` value (=4+6*100?) with a different structure with 6 Fe and 4 Pt?

2022-01-03 16:59 UTC, pzhanggit commented on hydragnn/preprocess/load_data.py
> +        frequencies = torch.bincount(data.x[:, 0].int())
Is `stratified_splitting` function specifically designed for cases that `data.x[:, 0]` are integers or can be uniquely represented by integers? For example, this line would fail to tell the different structures in unit tests, where`data.x[:,0]` is not greater than 1 for all nodes.

2022-01-03 17:07 UTC, pzhanggit commented on hydragnn/preprocess/load_data.py
> +        frequencies = torch.bincount(data.x[:, 0].int())
Btw, even for `lsms` data, `data.x[:,0]` is normalized between 0 and 1 at this point. So, the current counting works for binary alloy, i.e., with 0 and 1 `data.x[:,0]`, for but would fail for more than two atom types?

2022-01-03 17:12 UTC, pzhanggit requested changes
Not sure current `category` value is a unique representation of data structures (see the detailed comments.)

2022-01-03 17:16 UTC, streeve commented on hydragnn/preprocess/load_data.py
> +def stratified_splitting(dataset, perc_train):
Isn't this really `compositional_stratified_splitting`? It probably makes sense to have another `stratified_splitting` function that just wraps sklearn

2022-01-05 22:27 UTC, allaffa commented on hydragnn/preprocess/load_data.py
> +            category += frequency * (100 ** index)
> Is this representation unique? For example, a structure with 4 Fe atoms and 6 Pt atoms would have the same `category` value (=4+6*100?) with a different structure with 6 Fe and 4 Pt?

You are right. The representation is not unique. I need to fix this.

2022-01-05 22:30 UTC, allaffa commented on hydragnn/preprocess/load_data.py
> +def stratified_splitting(dataset, perc_train):
Yes, `compositional_stratified_splitting` is a more appropriate term. 
As to to having another` stratified_splitting` function that just wraps sklearn, do you have in mind anything specific?

2022-01-07 22:24 UTC, allaffa commented on hydragnn/preprocess/load_data.py
> +            category += frequency * (100 ** index)
@pzhanggit 
After the discussion we had to today where I explained to you the rationale behind the new categorization, let me know if the new version of the code addresses your comment.

2022-01-07 22:25 UTC, allaffa commented on hydragnn/preprocess/load_data.py
> +        frequencies = torch.bincount(data.x[:, 0].int())
@pzhanggit 
I use a dictionary now to map different elements rescaled proton numbers into integers.

2022-01-07 23:05 UTC, allaffa commented on hydragnn/preprocess/load_data.py
> +def stratified_splitting(dataset, perc_train):
> Isn't this really `compositional_stratified_splitting`? It probably makes sense to have another `stratified_splitting` function that just wraps sklearn

@streeve 
I changed the name of the function to `compositional_stratified_splitting` as you suggested

2022-01-10 15:12 UTC, allaffa commented on tests/inputs/ci.json
> +        "stratified_splitting": true,
@streeve 
Taken out :)

2022-01-10 15:35 UTC, pzhanggit commented on hydragnn/preprocess/load_data.py
> +    for data in dataset:
Wrap these lines into functions since they are used repeatedly below to generate val and test sets also

2022-01-10 19:32 UTC, allaffa commented on hydragnn/preprocess/load_data.py
> +    for data in dataset:
Done. :) Thanks.

2022-01-11 21:35 UTC, pzhanggit commented on hydragnn/preprocess/load_data.py
> +def get_max_graph_size(dataset: torch_geometric.data.dataset):
What is the type `torch_geometric.data.dataset`?

2022-01-11 21:43 UTC, pzhanggit commented on hydragnn/preprocess/load_data.py
> +    partition2_indices = []
```suggestion
```

2022-01-11 21:48 UTC, pzhanggit commented on hydragnn/preprocess/load_data.py
> +        elements = torch.unique(data.x[:, 0])
Currently `dataset_categories` is hard coded to be calculated by` data.x[:, 0]`. Could we make it optional? We might want to use a different variable for stratified splitting.

2022-01-11 21:52 UTC, pzhanggit approved these changes
Thanks for the changes. It is looks great to me now. Only one question about the variable used to stratified stratification, should it be optional?

2022-01-12 17:25 UTC, allaffa commented on hydragnn/preprocess/load_data.py
> +        elements = torch.unique(data.x[:, 0])
A few notes on this point: 
 
1) The quantity can be either an input or an output
2) the user has to specify where the quantity can be found the data (i.e. the index of the column). Different input formats impact this decision. To circumvent this, the choice of the labeling quantity has to happen on torch.geometric.data, meaning after the quantities are imported
3) Related to point 2, the user DOES not have direct knowledge of what the labeling quantity si going to end up in the torch.geometric.structure
4) The quantity has to be a scalar. I don't see how the splitting could be done using vectors as labels
5) The quantity used to split is not necessarily something we need to use also as a feature for predictions

2022-01-14 16:27 UTC, merged