Fixup tests
ORNL/HydraGNN pull request #93
Opened 2022-01-18 23:09 UTC by streeve

This PR does 3 main things:

- Updates unit test to set node features to "type" (integers) and node outputs to KNN aggregated features (previously only the linear values were not updated)
- Adds pytest step to remove all datasets (attempting to make sure we no longer have consistent failures on a given PR due to a particularly difficult to predict datset)
- Sets separate thresholds for CG with and without edge lengths (intended to be done when added...)

The rest is small cleanup ("clusters" is now "types", etc.)

2022-01-19 18:57 UTC, allaffa approved these changes

2022-01-19 18:57 UTC, allaffa commented on .github/workflows/CI.yml
> +          python -m pytest -rfEP -W error -W ignore::DeprecationWarning --tb=native
what does tb=native do?

2022-01-19 19:09 UTC, streeve commented on .github/workflows/CI.yml
> +          python -m pytest -rfEP -W error -W ignore::DeprecationWarning --tb=native
That just reduces the traceback output on failure. I was annoyed the pytest prints the entire function when it fails

2022-01-19 19:09 UTC, streeve commented
Looks like one of two tests is hanging - maybe an issue with what I added in `conftest` for MPI?

2022-01-19 19:14 UTC, streeve commented on tests/conftest.py
> +def pytest_configure(config):
To be clear, this removes all unit test data when pytest starts up. This is helpful for CI, but maybe not locally. Also likely the reason the CI is hanging

2022-01-19 20:47 UTC, pzhanggit commented on tests/test_graphs.py
> +        "CGCNN": [0.50, 0.20, 0.95],
Wow~

2022-01-19 20:49 UTC, pzhanggit commented on tests/test_graphs.py
> -                if sample_error < sample_error_min:
Good point, not sure were tracking this

2022-01-19 20:57 UTC, pzhanggit commented on tests/deterministic_graph_data.py
> +        node_output_x_square = node_feature ** 2
Is it purposely designed as `node_output_x_square = node_feature ** 2` to consider the contributions of node features, instead of `node_output_x_square = node_output_x **2`?

2022-01-20 23:08 UTC, streeve commented on tests/deterministic_graph_data.py
> +        node_output_x_square = node_feature ** 2
No, that's a mistake 🥇

2022-01-21 00:38 UTC, streeve commented on tests/deterministic_graph_data.py
> +        node_output_x_square = node_feature ** 2
Fixed

2022-01-21 04:08 UTC, allaffa requested changes

2022-01-21 04:08 UTC, allaffa commented on tests/test_graphs.py
> +        sample_error_avg = sample_error_sum / num_samples
I think this is the mean absolute error. 
It is totally ok to compute it manually, but I think you can also use built-in PyTorch capabilities to make your life easier. 
I would rename `sample_error_sum` in `mean_absolute_error`

2022-01-21 16:13 UTC, streeve commented on tests/test_graphs.py
> +        sample_error_avg = sample_error_sum / num_samples
Those are two very good points - I renamed and used torch for both to make it clearer and simpler

2022-01-21 16:52 UTC, allaffa requested changes

2022-01-21 16:52 UTC, allaffa commented on tests/test_graphs.py
> +        sample_max_error = torch.max(torch.abs(head_true - head_pred))
```suggestion
        sample_max_abs_error = torch.max(torch.abs(head_true - head_pred))
```

2022-01-21 16:52 UTC, allaffa commented on tests/test_graphs.py
> +            sample_max_error < thresholds[model_type][2]
```suggestion
            sample_max_abs_error < thresholds[model_type][2]
```

2022-01-21 16:52 UTC, allaffa commented on tests/test_graphs.py
> +            + "{:.6f}".format(sample_max_error)
```suggestion
            + "{:.6f}".format(sample_max_abs_error)
```

2022-01-21 16:53 UTC, allaffa commented
@streeve 
Added proposed commits to rename `sample_max_error` into `sample_max_abs_error`
After this change, for me this is ready to go as soon as tests pass.

2022-01-21 17:29 UTC, streeve commented
> Added proposed commits to rename `sample_max_error` into `sample_max_abs_error` After this change, for me this is ready to go as soon as tests pass.

Done - and also you need to approve :)

2022-01-21 18:32 UTC, pzhanggit approved these changes
Looks great, thanks!

2022-01-21 19:02 UTC, allaffa approved these changes

2022-01-21 19:02 UTC, allaffa commented
> > Added proposed commits to rename `sample_max_error` into `sample_max_abs_error` After this change, for me this is ready to go as soon as tests pass.
> 
> Done - and also you need to approve :)

Done.

2022-01-21 19:02 UTC, merged