Periodic boundary conditions
ORNL/HydraGNN pull request #94
Opened 2022-01-25 04:12 UTC by allaffa

The Atomic System Environment (ASE) is used to impose periodic boundary conditions using the minimum image convention.

2022-02-01 18:55 UTC, streeve requested changes
Way simpler than what I did and a useful library for other details too!

2022-02-01 18:55 UTC, streeve commented on hydragnn/preprocess/utils.py
> +            edge_src, edge_dst, edge_shift = ase.neighborlist.neighbor_list(
Do we plan to use the shifts somewhere specific? Maybe I'm misunderstanding how they return the distance info

2022-02-01 18:55 UTC, streeve commented on hydragnn/preprocess/utils.py
> +                "ijS", a=ase_atom_object, cutoff=self.r, self_interaction=self.loop
Can you add a comment on the "ijS"? I think I understand from the docs, but it's kind of a weird input

2022-02-01 18:55 UTC, streeve commented on hydragnn/preprocess/utils.py
> +class RadiusGraphPBC(RadiusGraph):
I really like this design

2022-02-01 18:55 UTC, streeve commented on hydragnn/preprocess/utils.py
> +    Args:
Do we not need to explicitly call the base constructor? Python is crazy

2022-02-01 18:55 UTC, streeve commented on hydragnn/preprocess/utils.py
> +        else:
Can we just move this else block outside the class (into SerializedLoader)?
```
if config.pbc: return RadiusGraphPBC
else: return RadiusGraph
```
Then we don't need to overload the constructor or store whether we're using PBC

2022-02-01 19:14 UTC, allaffa commented on examples/lsms/lsms.json
> +            "periodic_boundary_conditions": false,
For now, I would like to make a case for HydraGNN to be a surrogate for atomic modeling in general.
For some molecular dynamics application I do not think periodic boundary conditions (PBCs) make sense. I do not know what sense it would make to periodically replicate the same molecule over and over again. 
As I see it, PBCs make sense for alloys, but that is only one of the many families that fall under the "atomic modeling" umbrella.

2022-02-01 19:14 UTC, allaffa commented on hydragnn/preprocess/utils.py
> +            edge_src, edge_dst, edge_shift = ase.neighborlist.neighbor_list(
The shift is actually non used for now.

2022-02-01 19:14 UTC, allaffa commented on hydragnn/preprocess/utils.py
> +class RadiusGraphPBC(RadiusGraph):
Thanks :D

2022-02-01 19:18 UTC, allaffa commented on hydragnn/preprocess/utils.py
> +    Args:
If I understand correctly how Python works, one needs to explicitly call the base constructor if the child class has a constructor that can be seen as a "specialization" of the base class constructor. 
In this case, the specialized constructor for the child class would be exactly the same as the base class. In fact, I do not re-define the constructor at all. It's hidden from you :D 
But I think you are right. we should make sure that not explicitly calling the base constructor still ensures that everything is preserved from the base class as expected.

2022-02-01 19:28 UTC, allaffa commented on hydragnn/preprocess/utils.py
> +        else:
I thought about that indeed :)
If we move this if-then-else in the SerializedLoader, we will need to re-create the ASE atomic environment a second time to compute the edge attributes (if needed). 
If one applies PBC, one needs also to make sure that the edge lengths are computed correctly too. To apply both PBC and compute edge lengths, the ASE object is needed. So why not constructing the ASE object and extract everything needed out of it all at once?

2022-02-01 19:45 UTC, streeve commented on examples/lsms/lsms.json
> +            "periodic_boundary_conditions": false,
I think you mean "molecular application" and for that I completely agree. But this is the FePt example, which would likely be improved with PBC

2022-02-01 19:45 UTC, streeve commented on hydragnn/preprocess/utils.py
> +        else:
Can't we just check whether `edge_attr` exist before calling `Distance` in a similar way? I agree that it doesn't make sense to call multiple distance functions. Then we don't even need `DistancePBC`

2022-02-01 21:00 UTC, allaffa commented on hydragnn/preprocess/utils.py
> +        else:
`Distance` creates `edge_attr`. Before calling `Distance`, `edge_attr` does not exist. Moreover, `edge_attr` may contain attributes that are not related to the length of the bond. In that case, `edge_attr` already exists but distance needs to be called anyway to update the existing `edge_attr`

2022-02-01 21:43 UTC, allaffa commented on hydragnn/preprocess/utils.py
> +            edge_src, edge_dst, edge_shift = ase.neighborlist.neighbor_list(
@streeve I removed it :)

2022-02-01 21:45 UTC, allaffa commented on hydragnn/preprocess/utils.py
> +                "ijS", a=ase_atom_object, cutoff=self.r, self_interaction=self.loop
Comment added

2022-02-01 21:47 UTC, allaffa commented on examples/lsms/lsms.json
> +            "periodic_boundary_conditions": false,
Oh sorry. I thought you meant in general. 
I tried to play with PBC on the FePt. Unfortunately, we cannot. Because three years ago I generated the FePt data using 32 atoms. This system does not equally replicate the unit cell in all the x-y-z directions. This causes the ASE package to mess up the calculation of the PBC. 
In order for PBC to be calculated correctly, the system must replicate the unit cell in all x-y-z directions the same number of times. But I did not think about this three years ago. 

If I knew then what I know now :)

2022-02-02 23:27 UTC, streeve commented on examples/lsms/lsms.json
> +            "periodic_boundary_conditions": false,
We should just be able to pass a non-uniform cell to ASE - there's no requirement that PBC use uniform cells

2022-02-02 23:28 UTC, streeve commented on hydragnn/preprocess/utils.py
> +            data.edge_shift = torch.tensor(edge_shift)
Remove :)

2022-02-03 18:52 UTC, allaffa commented on examples/lsms/lsms.json
> +            "periodic_boundary_conditions": false,
Can you define what non-uniform cell is?

2022-02-03 19:01 UTC, allaffa commented on hydragnn/preprocess/serialized_dataset_loader.py
>          dataset[:] = [compute_edge_lengths(data) for data in dataset]
@streeve 
Differently from RadiusGraph the computes only the adjacency matrix WITHOUT computing the length of the edges, RadiusGraphPBC computes both the adjacency matrix AND the length of the edges. Therefore, once RadiusGraphPBC is called,  you do not need to call compute_edge_lengths anymore. 

Your changes are not valid

2022-02-03 19:06 UTC, streeve commented on hydragnn/preprocess/serialized_dataset_loader.py
>          dataset[:] = [compute_edge_lengths(data) for data in dataset]
Fixed, I think

2022-02-03 19:13 UTC, streeve commented on examples/lsms/lsms.json
> +            "periodic_boundary_conditions": false,
Because we have fixed angles, I mean a length 3 vector for the xyz lattice size instead of a single lattice parameter. The fully general case would be a 3x3 matrix with variable lengths and angles in xyz 
https://wiki.fysik.dtu.dk/ase/ase/atoms.html

2022-02-03 20:46 UTC, streeve commented on hydragnn/preprocess/serialized_dataset_loader.py
>          dataset[:] = [compute_edge_lengths(data) for data in dataset]
Discussed in call

2022-02-09 04:22 UTC, allaffa commented on tests/inputs/ci.json
> +            "periodic_boundary_conditions": false,
Ising model?

2022-03-04 20:34 UTC, streeve commented
Finally pushed a state that should work for now. As we discussed, we now have a test where there should be no periodic neighbors (isolated molecule) and one where every node has equal neighbors once PBC are applied. This does not handle cases where the system size is less than half the cutoff (quite common in DFT), but we can address that in the future

2022-03-04 20:35 UTC, allaffa commented
> Finally pushed a state that should work for now. As we discussed, we now have a test where there should be no periodic neighbors (isolated molecule) and one where every node has equal neighbors once PBC are applied. This does not handle cases where the system size is less than half the cutoff (quite common in DFT), but we can address that in the future

If unit tests pass, approve the PR. Since I created the PR, I cannot approve it myself.

2022-03-04 21:36 UTC, pzhanggit commented on hydragnn/preprocess/serialized_dataset_loader.py
> +            compute_edge_lengths = Distance(norm=False, cat=True)
repeated with line 84?

2022-03-04 22:48 UTC, streeve commented on hydragnn/preprocess/serialized_dataset_loader.py
> +            compute_edge_lengths = Distance(norm=False, cat=True)
Thanks, fixed

2022-03-04 22:49 UTC, streeve approved these changes

2022-03-04 22:55 UTC, streeve commented
I squashed some commits together, but left the most recent few to keep how you dealt with duplicates. I approved, but would prefer to wait until Pei also does

2022-03-07 18:03 UTC, merged